version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: gomod
    directory: /paxeer-network
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: gomod
    directory: /paxeer-network/hpx/registry
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: gomod
    directory: /paxeer-network/sdk/cosmovisor
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: gomod
    directory: /paxeer-network/sdk/ics23
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: npm
    directory: /paxeer-network/contracts
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /paxeer-network/integration_test/dapp_tests
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: npm
    directory: /paxeer-network/integration_test/rpc_tests
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: cargo
    directory: /paxeer-network/wasm-runtime/libwasmvm
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
