import { DocsLayout } from '@/components/DocsLayout'
import Link from 'next/link'

export default function Configuration() {
  return (
    <DocsLayout>
      <div className="page-header">
        <h1 className="page-title">Configuration</h1>
        <p className="page-description">
          Configuring paxd through config.toml, app.toml, node modes, and environment variables.
        </p>
      </div>

      <div className="source-note">
        <strong>Source:</strong> <code>paxeer-network/node/params/config.go</code>, <code>docker/localnode/config/</code>, <code>config.yml</code>
      </div>

      <h2>Configuration Files</h2>

      <p>
        Paxeer nodes are configured through two main TOML files generated by <code>paxd init</code>:
      </p>

      <table>
        <thead>
          <tr>
            <th>File</th>
            <th>Location</th>
            <th>Purpose</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><code>config.toml</code></td>
            <td><code>~/.paxd/config/</code></td>
            <td>Tendermint consensus, P2P, RPC, mempool settings</td>
          </tr>
          <tr>
            <td><code>app.toml</code></td>
            <td><code>~/.paxd/config/</code></td>
            <td>Application config: API, gRPC, pruning, telemetry, EVM</td>
          </tr>
          <tr>
            <td><code>genesis.json</code></td>
            <td><code>~/.paxd/config/</code></td>
            <td>Genesis state and chain parameters</td>
          </tr>
        </tbody>
      </table>

      <h2>Node Modes</h2>

      <p>
        Paxeer supports four node modes with distinct configuration profiles:
      </p>

      <table>
        <thead>
          <tr>
            <th>Mode</th>
            <th>Purpose</th>
            <th>Services</th>
            <th>Indexing</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><strong>validator</strong></td>
            <td>Participate in consensus, sign blocks</td>
            <td>Minimal (security)</td>
            <td>Disabled</td>
          </tr>
          <tr>
            <td><strong>full</strong></td>
            <td>Serve queries, maintain recent history</td>
            <td>API, gRPC, RPC enabled</td>
            <td>KV indexer</td>
          </tr>
          <tr>
            <td><strong>archive</strong></td>
            <td>Keep complete history, no pruning</td>
            <td>API, gRPC, RPC enabled</td>
            <td>KV indexer</td>
          </tr>
          <tr>
            <td><strong>seed</strong></td>
            <td>Peer discovery only (1000 connections)</td>
            <td>Minimal</td>
            <td>Disabled</td>
          </tr>
        </tbody>
      </table>

      <div className="source-note">
        <strong>Implementation:</strong> <code>node/params/config.go</code> — <code>SetTendermintConfigByMode</code>, <code>SetAppConfigByMode</code>
      </div>

      <h2>config.toml (Tendermint)</h2>

      <h3>Base Settings</h3>

      <pre><code>{`# Node identifier (human-readable)
moniker = "pax-node-0"

# Node mode: validator | full | seed
mode = "validator"

# Database backend: goleveldb | rocksdb | badgerdb
db-backend = "goleveldb"

# Database directory (relative to home)
db-dir = "data"

# Logging
log-level = "info"
log-format = "plain"  # plain | json`}</code></pre>

      <h3>RPC Settings</h3>

      <pre><code>{`[rpc]
# RPC listen address
laddr = "tcp://0.0.0.0:26657"

# CORS (set to ["*"] for public nodes)
cors-allowed-origins = []

# Max simultaneous connections
max-open-connections = 900`}</code></pre>

      <h3>P2P Settings</h3>

      <pre><code>{`[p2p]
# P2P listen address
laddr = "tcp://0.0.0.0:26656"

# Seed nodes (comma-separated)
seeds = ""

# Persistent peers (comma-separated)
persistent-peers = ""

# Max inbound peers
max-num-inbound-peers = 40

# Max outbound peers
max-num-outbound-peers = 10`}</code></pre>

      <h3>Mempool Settings</h3>

      <pre><code>{`[mempool]
# Recheck transactions after each block
recheck = true

# Broadcast transactions to peers
broadcast = true

# Max transactions in mempool
size = 5000

# Max transaction bytes
max-txs-bytes = 1073741824`}</code></pre>

      <div className="source-note">
        <strong>Template:</strong> <code>docker/localnode/config/config.toml</code>
      </div>

      <h2>app.toml (Application)</h2>

      <h3>Base Settings</h3>

      <pre><code>{`# Minimum gas prices (reject txs below this)
minimum-gas-prices = "0.01uhpx"

# Pruning strategy: default | nothing | everything | custom
pruning = "nothing"

# Halt at block height (0 = disabled)
halt-height = 0

# Min blocks to retain (Tendermint pruning)
min-retain-blocks = 4000

# Inter-block caching
inter-block-cache = true`}</code></pre>

      <h3>Concurrency Settings</h3>

      <pre><code>{`# Concurrent transaction execution workers
concurrency-workers = 4

# Optimistic Concurrency Control (OCC)
occ-enabled = true`}</code></pre>

      <div className="source-note">
        <strong>OCC:</strong> Enables parallel transaction execution with conflict detection
      </div>

      <h3>API Settings</h3>

      <pre><code>{`[api]
# Enable REST API
enable = true

# API listen address
address = "tcp://0.0.0.0:1317"

# Enable Swagger docs
swagger = false

# Max open connections
max-open-connections = 1000

# Enable CORS (unsafe for public)
enabled-unsafe-cors = true`}</code></pre>

      <h3>gRPC Settings</h3>

      <pre><code>{`[grpc]
# Enable gRPC server
enable = true

# gRPC listen address
address = "0.0.0.0:9090"

[grpc-web]
# Enable gRPC-web (requires gRPC enabled)
enable = true

# gRPC-web listen address
address = "0.0.0.0:9091"

# Enable CORS (unsafe for public)
enable-unsafe-cors = true`}</code></pre>

      <h3>State Sync Settings</h3>

      <pre><code>{`[state-sync]
# Snapshot interval (blocks, 0 = disabled)
snapshot-interval = 100

# Keep N recent snapshots (0 = keep all)
snapshot-keep-recent = 3

# Snapshot directory override
snapshot-directory = ""`}</code></pre>

      <h3>Telemetry Settings</h3>

      <pre><code>{`[telemetry]
# Enable telemetry
enabled = true

# Prometheus retention (seconds)
prometheus-retention-time = 5

# Add hostname to metrics
enable-hostname = false

# Service name prefix
service-name = ""`}</code></pre>

      <h3>EVM Settings</h3>

      <pre><code>{`[evm]
# Enable EVM JSON-RPC (HTTP)
http-enabled = true

# Enable EVM JSON-RPC (WebSocket)
ws-enabled = true

# HTTP listen address
http-address = "0.0.0.0:8545"

# WebSocket listen address
ws-address = "0.0.0.0:8546"

# Legacy pax_ API allowlist (deprecated)
enabled-legacy-pax-apis = [
  "pax_getEVMAddressByCosmosAddress",
  "pax_getCosmosAddressByEVMAddress",
  "pax_getEVMInfo"
]`}</code></pre>

      <div className="source-note">
        <strong>Source:</strong> <code>docker/localnode/config/app.toml</code>, <code>rpc/config</code>
      </div>

      <h2>Node Mode Configuration</h2>

      <h3>Validator Nodes</h3>

      <pre><code>{`# config.toml
mode = "validator"

[tx-index]
indexer = ["null"]  # Validators don't need indexing

[p2p]
allow-duplicate-ip = false

# app.toml
[api]
enable = false  # Minimize services for security

[grpc]
enable = false

[state-store]
enable = false`}</code></pre>

      <h3>Full Nodes</h3>

      <pre><code>{`# config.toml
mode = "full"

[tx-index]
indexer = ["kv"]  # Enable transaction indexing

[rpc]
laddr = "tcp://0.0.0.0:26657"

# app.toml
[api]
enable = true

[grpc]
enable = true

[state-store]
enable = true
keep-recent = 100000  # Keep 100k recent blocks

min-retain-blocks = 100000

pruning = "nothing"  # Keep all state history`}</code></pre>

      <h3>Archive Nodes</h3>

      <pre><code>{`# config.toml
mode = "full"  # Tendermint doesn't recognize "archive"

[tx-index]
indexer = ["kv"]

# app.toml
[state-store]
enable = true
keep-recent = 0  # 0 = keep all history

min-retain-blocks = 0  # Keep all Tendermint blocks

pruning = "nothing"  # Keep all state`}</code></pre>

      <div className="source-note">
        <strong>Implementation:</strong> <code>node/params/config.go:180-196</code>
      </div>

      <h2>Address Prefixes</h2>

      <p>
        Paxeer uses <code>pax</code> Bech32 prefixes:
      </p>

      <ul>
        <li><strong>Account:</strong> <code>pax...</code></li>
        <li><strong>Validator operator:</strong> <code>paxvaloper...</code></li>
        <li><strong>Consensus node:</strong> <code>paxvalcons...</code></li>
      </ul>

      <div className="source-note">
        <strong>Source:</strong> <code>node/params/config.go:20-39</code>
      </div>

      <h2>Native Denominations</h2>

      <table>
        <thead>
          <tr>
            <th>Unit</th>
            <th>Exponent</th>
            <th>Symbol</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>uhpx (micro)</td>
            <td>10^-6</td>
            <td>Base unit (on-chain)</td>
          </tr>
          <tr>
            <td>hpx</td>
            <td>10^0</td>
            <td>Human unit</td>
          </tr>
        </tbody>
      </table>

      <p>
        1 hpx = 1,000,000 uhpx
      </p>

      <div className="source-note">
        <strong>Source:</strong> <code>node/params/config.go:13-18</code>
      </div>

      <h2>Environment Variables</h2>

      <h3>Docker Compose</h3>

      <pre><code>{`# Minimum gas prices
MIN_GAS_PRICES="0.01uhpx"

# Chain ID
CHAIN_ID="hyperpax_125-1"

# Moniker
MONIKER="pax-node"

# Node mode
NODE_MODE="validator"  # validator | full | archive | seed`}</code></pre>

      <h3>HPX Installer</h3>

      <pre><code>{`# Node type
HPX_TYPE=fullnode  # fullnode | validator

# Mirror (only for trusted alternate mirrors)
HPX_MIRROR=https://node.hyperpaxeer.com

# Runtime config source
HPX_RUNTIME_CONFIG_DIR=/root/.paxeer/config`}</code></pre>

      <div className="source-note">
        <strong>Source:</strong> <code>hpx/README.md</code>
      </div>

      <h2>Configuration Precedence</h2>

      <ol>
        <li><strong>Command-line flags</strong> (highest priority)</li>
        <li><strong>Environment variables</strong></li>
        <li><strong>app.toml</strong> and <code>config.toml</code></li>
        <li><strong>Defaults</strong> (lowest priority)</li>
      </ol>

      <h2>Validation</h2>

      <p>
        Validate configuration after editing:
      </p>

      <pre><code>{`paxd start --dry-run`}</code></pre>

      <p>
        This checks configuration syntax and module initialization without starting the node.
      </p>

      <div className="prev-next">
        <Link href="/run-node">
          <div className="prev-next-label">Previous</div>
          <div className="prev-next-title">Run a Node</div>
        </Link>
        <Link href="/operators">
          <div className="prev-next-label">Next</div>
          <div className="prev-next-title">Operators Guide</div>
        </Link>
      </div>
    </DocsLayout>
  )
}
