[package]
name = "layerx-platform-identity"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "layerx-identity"
path = "src/main.rs"

[dependencies]
getrandom.workspace = true
serde.workspace = true
serde_json.workspace = true
rustls.workspace = true
native-tls.workspace = true
sha2.workspace = true
subtle.workspace = true
zeroize.workspace = true

[lints]
workspace = true
