[package]
name = "layerx-proof"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
layerx-types = { path = "../layerx-types" }
layerx-wire = { path = "../layerx-wire" }
layerx-crypto = { path = "../layerx-crypto" }

[lints]
workspace = true
