// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: evm/config.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// XXTime fields indicate upgrade timestamps. For example, a ShanghaiTime
// of 42198537129 means the chain upgraded to the Shanghai version at timestamp 42198537129.
// A value of 0 means the upgrade is included in the genesis of the EVM on Pax.
// -1 means upgrade not reached yet.
type ChainConfig struct {
	CancunTime             int64  `protobuf:"varint,1,opt,name=cancun_time,json=cancunTime,proto3" json:"cancun_time,omitempty" yaml:"cancun_time"`
	PragueTime             int64  `protobuf:"varint,2,opt,name=prague_time,json=pragueTime,proto3" json:"prague_time,omitempty" yaml:"prague_time"`
	VerkleTime             int64  `protobuf:"varint,3,opt,name=verkle_time,json=verkleTime,proto3" json:"verkle_time,omitempty" yaml:"verkle_time"`
	PaxSstoreSetGasEip2200 uint64 `protobuf:"varint,4,opt,name=pax_sstore_set_gas_eip2200,json=paxSstoreSetGasEip2200,proto3" json:"pax_sstore_set_gas_eip2200,omitempty"`
}

func (m *ChainConfig) Reset()         { *m = ChainConfig{} }
func (m *ChainConfig) String() string { return proto.CompactTextString(m) }
func (*ChainConfig) ProtoMessage()    {}
func (*ChainConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_95b591dca6bd862e, []int{0}
}
func (m *ChainConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ChainConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ChainConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ChainConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainConfig.Merge(m, src)
}
func (m *ChainConfig) XXX_Size() int {
	return m.Size()
}
func (m *ChainConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ChainConfig proto.InternalMessageInfo

func (m *ChainConfig) GetCancunTime() int64 {
	if m != nil {
		return m.CancunTime
	}
	return 0
}

func (m *ChainConfig) GetPragueTime() int64 {
	if m != nil {
		return m.PragueTime
	}
	return 0
}

func (m *ChainConfig) GetVerkleTime() int64 {
	if m != nil {
		return m.VerkleTime
	}
	return 0
}

func (m *ChainConfig) GetPaxSstoreSetGasEip2200() uint64 {
	if m != nil {
		return m.PaxSstoreSetGasEip2200
	}
	return 0
}

func init() {
	proto.RegisterType((*ChainConfig)(nil), "paxprotocol.paxchain.evm.ChainConfig")
}

func init() { proto.RegisterFile("evm/config.proto", fileDescriptor_95b591dca6bd862e) }

var fileDescriptor_95b591dca6bd862e = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x31, 0x4f, 0x02, 0x31,
	0x18, 0x86, 0xa9, 0x10, 0x87, 0xb2, 0x18, 0x62, 0x08, 0x61, 0x38, 0xc9, 0x4d, 0x2c, 0xdc, 0x11,
	0x1c, 0x34, 0x8c, 0x10, 0xe3, 0x7e, 0x38, 0xb9, 0x5c, 0x3e, 0x8e, 0xcf, 0xd2, 0x70, 0xbd, 0x36,
	0x6d, 0x0f, 0x8f, 0x7f, 0xe1, 0xcf, 0x72, 0x64, 0x74, 0x32, 0x06, 0xfe, 0x81, 0xf1, 0x07, 0x98,
	0x6b, 0x35, 0x21, 0x6c, 0xef, 0x9b, 0xe7, 0x7d, 0x3a, 0xf4, 0xa3, 0x57, 0xb8, 0x15, 0x71, 0x26,
	0x8b, 0x17, 0xce, 0x22, 0xa5, 0xa5, 0x95, 0x9d, 0x9e, 0x82, 0xca, 0xa5, 0x4c, 0xe6, 0x91, 0x82,
	0x2a, 0x5b, 0x03, 0x2f, 0x22, 0xdc, 0x8a, 0xfe, 0x35, 0x93, 0x4c, 0x3a, 0x14, 0xd7, 0xc9, 0xef,
	0xc3, 0x1f, 0x42, 0xdb, 0xf3, 0x7a, 0x33, 0x77, 0xaf, 0x74, 0xee, 0x68, 0x3b, 0x83, 0x22, 0x2b,
	0x8b, 0xd4, 0x72, 0x81, 0x3d, 0x32, 0x20, 0xc3, 0xe6, 0xac, 0xfb, 0xfd, 0x79, 0xd3, 0xd9, 0x81,
	0xc8, 0xa7, 0xe1, 0x09, 0x0c, 0x13, 0xea, 0xdb, 0x13, 0x17, 0x58, 0x8b, 0x4a, 0x03, 0x2b, 0xd1,
	0x8b, 0x17, 0xe7, 0xe2, 0x09, 0x0c, 0x13, 0xea, 0xdb, 0xbf, 0xb8, 0x45, 0xbd, 0xc9, 0xff, 0xc4,
	0xe6, 0xb9, 0x78, 0x02, 0xc3, 0x84, 0xfa, 0xe6, 0xc4, 0x29, 0xed, 0x2b, 0xa8, 0x52, 0x63, 0xac,
	0xd4, 0x98, 0x1a, 0xb4, 0x29, 0x03, 0x93, 0x22, 0x57, 0x93, 0xc9, 0x78, 0xdc, 0x6b, 0x0d, 0xc8,
	0xb0, 0x95, 0x74, 0x15, 0x54, 0x0b, 0x37, 0x58, 0xa0, 0x7d, 0x04, 0xf3, 0xe0, 0xe9, 0x2c, 0x79,
	0x3f, 0x04, 0x64, 0x7f, 0x08, 0xc8, 0xd7, 0x21, 0x20, 0x6f, 0xc7, 0xa0, 0xb1, 0x3f, 0x06, 0x8d,
	0x8f, 0x63, 0xd0, 0x78, 0xbe, 0x67, 0xdc, 0xae, 0xcb, 0x65, 0x94, 0x49, 0x11, 0x1b, 0xbe, 0xe2,
	0x52, 0xc3, 0x28, 0x87, 0xa5, 0x89, 0x15, 0x54, 0x88, 0x7a, 0x54, 0xa0, 0x7d, 0x95, 0x7a, 0x13,
	0x0b, 0xb9, 0x2a, 0x73, 0x34, 0x71, 0x7d, 0x01, 0xbb, 0x53, 0x68, 0x96, 0x97, 0xee, 0x47, 0x6f,
	0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x05, 0x8c, 0xa7, 0x95, 0x01, 0x00, 0x00,
}

func (m *ChainConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChainConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ChainConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PaxSstoreSetGasEip2200 != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.PaxSstoreSetGasEip2200))
		i--
		dAtA[i] = 0x20
	}
	if m.VerkleTime != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.VerkleTime))
		i--
		dAtA[i] = 0x18
	}
	if m.PragueTime != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.PragueTime))
		i--
		dAtA[i] = 0x10
	}
	if m.CancunTime != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.CancunTime))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintConfig(dAtA []byte, offset int, v uint64) int {
	offset -= sovConfig(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ChainConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CancunTime != 0 {
		n += 1 + sovConfig(uint64(m.CancunTime))
	}
	if m.PragueTime != 0 {
		n += 1 + sovConfig(uint64(m.PragueTime))
	}
	if m.VerkleTime != 0 {
		n += 1 + sovConfig(uint64(m.VerkleTime))
	}
	if m.PaxSstoreSetGasEip2200 != 0 {
		n += 1 + sovConfig(uint64(m.PaxSstoreSetGasEip2200))
	}
	return n
}

func sovConfig(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozConfig(x uint64) (n int) {
	return sovConfig(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ChainConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChainConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChainConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CancunTime", wireType)
			}
			m.CancunTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CancunTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PragueTime", wireType)
			}
			m.PragueTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PragueTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerkleTime", wireType)
			}
			m.VerkleTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VerkleTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaxSstoreSetGasEip2200", wireType)
			}
			m.PaxSstoreSetGasEip2200 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PaxSstoreSetGasEip2200 |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipConfig(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthConfig
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupConfig
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthConfig
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthConfig        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowConfig          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupConfig = fmt.Errorf("proto: unexpected end of group")
)
