// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: evm/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_sidiora_labs_paxeer_network_sdk_types "github.com/sidiora-labs/paxeer-network/sdk/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module
type Params struct {
	// string base_denom = 1 [
	//   (gogoproto.moretags)   = "yaml:\"base_denom\"",
	//   (gogoproto.jsontag) = "base_denom"
	// ];
	PriorityNormalizer github_com_sidiora_labs_paxeer_network_sdk_types.Dec `protobuf:"bytes,2,opt,name=priority_normalizer,json=priorityNormalizer,proto3,customtype=github.com/sidiora-labs/paxeer-network/sdk/types.Dec" json:"priority_normalizer" yaml:"priority_normalizer"`
	BaseFeePerGas      github_com_sidiora_labs_paxeer_network_sdk_types.Dec `protobuf:"bytes,3,opt,name=base_fee_per_gas,json=baseFeePerGas,proto3,customtype=github.com/sidiora-labs/paxeer-network/sdk/types.Dec" json:"base_fee_per_gas" yaml:"base_fee_per_gas"`
	MinimumFeePerGas   github_com_sidiora_labs_paxeer_network_sdk_types.Dec `protobuf:"bytes,4,opt,name=minimum_fee_per_gas,json=minimumFeePerGas,proto3,customtype=github.com/sidiora-labs/paxeer-network/sdk/types.Dec" json:"minimum_fee_per_gas" yaml:"minimum_fee_per_gas"`
	// ChainConfig chain_config = 5 [(gogoproto.moretags) = "yaml:\"chain_config\"", (gogoproto.nullable) = false];
	//   string chain_id = 6 [
	//   (gogoproto.moretags)   = "yaml:\"chain_id\"",
	//   (gogoproto.customtype) = "github.com/sidiora-labs/paxeer-network/sdk/types.Int",
	//   (gogoproto.nullable)   = false,
	//   (gogoproto.jsontag) = "chain_id"
	// ];
	// repeated string whitelisted_codehashes_bank_send = 7 [
	//   (gogoproto.moretags)   = "yaml:\"whitelisted_codehashes_bank_send\"",
	//   (gogoproto.jsontag) = "whitelisted_codehashes_bank_send"
	// ];
	WhitelistedCwCodeHashesForDelegateCall [][]byte                                             `protobuf:"bytes,8,rep,name=whitelisted_cw_code_hashes_for_delegate_call,json=whitelistedCwCodeHashesForDelegateCall,proto3" json:"whitelisted_cw_code_hashes_for_delegate_call" yaml:"whitelisted_cw_code_hashes_for_delegate_call"`
	DeliverTxHookWasmGasLimit              uint64                                               `protobuf:"varint,9,opt,name=deliver_tx_hook_wasm_gas_limit,json=deliverTxHookWasmGasLimit,proto3" json:"deliver_tx_hook_wasm_gas_limit,omitempty"`
	MaxDynamicBaseFeeUpwardAdjustment      github_com_sidiora_labs_paxeer_network_sdk_types.Dec `protobuf:"bytes,10,opt,name=max_dynamic_base_fee_upward_adjustment,json=maxDynamicBaseFeeUpwardAdjustment,proto3,customtype=github.com/sidiora-labs/paxeer-network/sdk/types.Dec" json:"max_dynamic_base_fee_upward_adjustment" yaml:"max_dynamic_base_fee_upward_adjustment"`
	MaxDynamicBaseFeeDownwardAdjustment    github_com_sidiora_labs_paxeer_network_sdk_types.Dec `protobuf:"bytes,11,opt,name=max_dynamic_base_fee_downward_adjustment,json=maxDynamicBaseFeeDownwardAdjustment,proto3,customtype=github.com/sidiora-labs/paxeer-network/sdk/types.Dec" json:"max_dynamic_base_fee_downward_adjustment" yaml:"max_dynamic_base_fee_downward_adjustment"`
	TargetGasUsedPerBlock                  uint64                                               `protobuf:"varint,12,opt,name=target_gas_used_per_block,json=targetGasUsedPerBlock,proto3" json:"target_gas_used_per_block,omitempty"`
	MaximumFeePerGas                       github_com_sidiora_labs_paxeer_network_sdk_types.Dec `protobuf:"bytes,13,opt,name=maximum_fee_per_gas,json=maximumFeePerGas,proto3,customtype=github.com/sidiora-labs/paxeer-network/sdk/types.Dec" json:"maximum_fee_per_gas" yaml:"maximum_fee_per_gas"`
	RegisterPointerDisabled                bool                                                 `protobuf:"varint,14,opt,name=register_pointer_disabled,json=registerPointerDisabled,proto3" json:"register_pointer_disabled" yaml:"register_pointer_disabled"`
	PaxSstoreSetGasEip2200                 uint64                                               `protobuf:"varint,15,opt,name=pax_sstore_set_gas_eip2200,json=paxSstoreSetGasEip2200,proto3" json:"pax_sstore_set_gas_eip2200,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_9272f3679901ea94, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetWhitelistedCwCodeHashesForDelegateCall() [][]byte {
	if m != nil {
		return m.WhitelistedCwCodeHashesForDelegateCall
	}
	return nil
}

func (m *Params) GetDeliverTxHookWasmGasLimit() uint64 {
	if m != nil {
		return m.DeliverTxHookWasmGasLimit
	}
	return 0
}

func (m *Params) GetTargetGasUsedPerBlock() uint64 {
	if m != nil {
		return m.TargetGasUsedPerBlock
	}
	return 0
}

func (m *Params) GetRegisterPointerDisabled() bool {
	if m != nil {
		return m.RegisterPointerDisabled
	}
	return false
}

func (m *Params) GetPaxSstoreSetGasEip2200() uint64 {
	if m != nil {
		return m.PaxSstoreSetGasEip2200
	}
	return 0
}

type ParamsPreV580 struct {
	// string base_denom = 1 [
	//
	//	(gogoproto.moretags)   = "yaml:\"base_denom\"",
	//	(gogoproto.jsontag) = "base_denom"
	//
	// ];
	PriorityNormalizer github_com_sidiora_labs_paxeer_network_sdk_types.Dec `protobuf:"bytes,2,opt,name=priority_normalizer,json=priorityNormalizer,proto3,customtype=github.com/sidiora-labs/paxeer-network/sdk/types.Dec" json:"priority_normalizer" yaml:"priority_normalizer"`
	BaseFeePerGas      github_com_sidiora_labs_paxeer_network_sdk_types.Dec `protobuf:"bytes,3,opt,name=base_fee_per_gas,json=baseFeePerGas,proto3,customtype=github.com/sidiora-labs/paxeer-network/sdk/types.Dec" json:"base_fee_per_gas" yaml:"base_fee_per_gas"`
	MinimumFeePerGas   github_com_sidiora_labs_paxeer_network_sdk_types.Dec `protobuf:"bytes,4,opt,name=minimum_fee_per_gas,json=minimumFeePerGas,proto3,customtype=github.com/sidiora-labs/paxeer-network/sdk/types.Dec" json:"minimum_fee_per_gas" yaml:"minimum_fee_per_gas"`
	// ChainConfig chain_config = 5 [(gogoproto.moretags) = "yaml:\"chain_config\"", (gogoproto.nullable) = false];
	//
	//	string chain_id = 6 [
	//	(gogoproto.moretags)   = "yaml:\"chain_id\"",
	//	(gogoproto.customtype) = "github.com/sidiora-labs/paxeer-network/sdk/types.Int",
	//	(gogoproto.nullable)   = false,
	//	(gogoproto.jsontag) = "chain_id"
	//
	// ];
	// repeated string whitelisted_codehashes_bank_send = 7 [
	//
	//	(gogoproto.moretags)   = "yaml:\"whitelisted_codehashes_bank_send\"",
	//	(gogoproto.jsontag) = "whitelisted_codehashes_bank_send"
	//
	// ];
	WhitelistedCwCodeHashesForDelegateCall [][]byte `protobuf:"bytes,8,rep,name=whitelisted_cw_code_hashes_for_delegate_call,json=whitelistedCwCodeHashesForDelegateCall,proto3" json:"whitelisted_cw_code_hashes_for_delegate_call" yaml:"whitelisted_cw_code_hashes_for_delegate_call"`
}

func (m *ParamsPreV580) Reset()      { *m = ParamsPreV580{} }
func (*ParamsPreV580) ProtoMessage() {}
func (*ParamsPreV580) Descriptor() ([]byte, []int) {
	return fileDescriptor_9272f3679901ea94, []int{1}
}
func (m *ParamsPreV580) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ParamsPreV580) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ParamsPreV580.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ParamsPreV580) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParamsPreV580.Merge(m, src)
}
func (m *ParamsPreV580) XXX_Size() int {
	return m.Size()
}
func (m *ParamsPreV580) XXX_DiscardUnknown() {
	xxx_messageInfo_ParamsPreV580.DiscardUnknown(m)
}

var xxx_messageInfo_ParamsPreV580 proto.InternalMessageInfo

func (m *ParamsPreV580) GetWhitelistedCwCodeHashesForDelegateCall() [][]byte {
	if m != nil {
		return m.WhitelistedCwCodeHashesForDelegateCall
	}
	return nil
}

type ParamsPreV600 struct {
	// string base_denom = 1 [
	//
	//	(gogoproto.moretags)   = "yaml:\"base_denom\"",
	//	(gogoproto.jsontag) = "base_denom"
	//
	// ];
	PriorityNormalizer        github_com_sidiora_labs_paxeer_network_sdk_types.Dec `protobuf:"bytes,2,opt,name=priority_normalizer,json=priorityNormalizer,proto3,customtype=github.com/sidiora-labs/paxeer-network/sdk/types.Dec" json:"priority_normalizer" yaml:"priority_normalizer"`
	BaseFeePerGas             github_com_sidiora_labs_paxeer_network_sdk_types.Dec `protobuf:"bytes,3,opt,name=base_fee_per_gas,json=baseFeePerGas,proto3,customtype=github.com/sidiora-labs/paxeer-network/sdk/types.Dec" json:"base_fee_per_gas" yaml:"base_fee_per_gas"`
	MinimumFeePerGas          github_com_sidiora_labs_paxeer_network_sdk_types.Dec `protobuf:"bytes,4,opt,name=minimum_fee_per_gas,json=minimumFeePerGas,proto3,customtype=github.com/sidiora-labs/paxeer-network/sdk/types.Dec" json:"minimum_fee_per_gas" yaml:"minimum_fee_per_gas"`
	DeliverTxHookWasmGasLimit uint64                                               `protobuf:"varint,5,opt,name=deliver_tx_hook_wasm_gas_limit,json=deliverTxHookWasmGasLimit,proto3" json:"deliver_tx_hook_wasm_gas_limit,omitempty"`
	// ChainConfig chain_config = 5 [(gogoproto.moretags) = "yaml:\"chain_config\"", (gogoproto.nullable) = false];
	//
	//	string chain_id = 6 [
	//	(gogoproto.moretags)   = "yaml:\"chain_id\"",
	//	(gogoproto.customtype) = "github.com/sidiora-labs/paxeer-network/sdk/types.Int",
	//	(gogoproto.nullable)   = false,
	//	(gogoproto.jsontag) = "chain_id"
	//
	// ];
	// repeated string whitelisted_codehashes_bank_send = 7 [
	//
	//	(gogoproto.moretags)   = "yaml:\"whitelisted_codehashes_bank_send\"",
	//	(gogoproto.jsontag) = "whitelisted_codehashes_bank_send"
	//
	// ];
	WhitelistedCwCodeHashesForDelegateCall [][]byte `protobuf:"bytes,8,rep,name=whitelisted_cw_code_hashes_for_delegate_call,json=whitelistedCwCodeHashesForDelegateCall,proto3" json:"whitelisted_cw_code_hashes_for_delegate_call" yaml:"whitelisted_cw_code_hashes_for_delegate_call"`
}

func (m *ParamsPreV600) Reset()      { *m = ParamsPreV600{} }
func (*ParamsPreV600) ProtoMessage() {}
func (*ParamsPreV600) Descriptor() ([]byte, []int) {
	return fileDescriptor_9272f3679901ea94, []int{2}
}
func (m *ParamsPreV600) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ParamsPreV600) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ParamsPreV600.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ParamsPreV600) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParamsPreV600.Merge(m, src)
}
func (m *ParamsPreV600) XXX_Size() int {
	return m.Size()
}
func (m *ParamsPreV600) XXX_DiscardUnknown() {
	xxx_messageInfo_ParamsPreV600.DiscardUnknown(m)
}

var xxx_messageInfo_ParamsPreV600 proto.InternalMessageInfo

func (m *ParamsPreV600) GetDeliverTxHookWasmGasLimit() uint64 {
	if m != nil {
		return m.DeliverTxHookWasmGasLimit
	}
	return 0
}

func (m *ParamsPreV600) GetWhitelistedCwCodeHashesForDelegateCall() [][]byte {
	if m != nil {
		return m.WhitelistedCwCodeHashesForDelegateCall
	}
	return nil
}

type ParamsPreV601 struct {
	// string base_denom = 1 [
	//
	//	(gogoproto.moretags)   = "yaml:\"base_denom\"",
	//	(gogoproto.jsontag) = "base_denom"
	//
	// ];
	PriorityNormalizer github_com_sidiora_labs_paxeer_network_sdk_types.Dec `protobuf:"bytes,2,opt,name=priority_normalizer,json=priorityNormalizer,proto3,customtype=github.com/sidiora-labs/paxeer-network/sdk/types.Dec" json:"priority_normalizer" yaml:"priority_normalizer"`
	BaseFeePerGas      github_com_sidiora_labs_paxeer_network_sdk_types.Dec `protobuf:"bytes,3,opt,name=base_fee_per_gas,json=baseFeePerGas,proto3,customtype=github.com/sidiora-labs/paxeer-network/sdk/types.Dec" json:"base_fee_per_gas" yaml:"base_fee_per_gas"`
	MinimumFeePerGas   github_com_sidiora_labs_paxeer_network_sdk_types.Dec `protobuf:"bytes,4,opt,name=minimum_fee_per_gas,json=minimumFeePerGas,proto3,customtype=github.com/sidiora-labs/paxeer-network/sdk/types.Dec" json:"minimum_fee_per_gas" yaml:"minimum_fee_per_gas"`
	// ChainConfig chain_config = 5 [(gogoproto.moretags) = "yaml:\"chain_config\"", (gogoproto.nullable) = false];
	//
	//	string chain_id = 6 [
	//	(gogoproto.moretags)   = "yaml:\"chain_id\"",
	//	(gogoproto.customtype) = "github.com/sidiora-labs/paxeer-network/sdk/types.Int",
	//	(gogoproto.nullable)   = false,
	//	(gogoproto.jsontag) = "chain_id"
	//
	// ];
	// repeated string whitelisted_codehashes_bank_send = 7 [
	//
	//	(gogoproto.moretags)   = "yaml:\"whitelisted_codehashes_bank_send\"",
	//	(gogoproto.jsontag) = "whitelisted_codehashes_bank_send"
	//
	// ];
	WhitelistedCwCodeHashesForDelegateCall [][]byte                                             `protobuf:"bytes,8,rep,name=whitelisted_cw_code_hashes_for_delegate_call,json=whitelistedCwCodeHashesForDelegateCall,proto3" json:"whitelisted_cw_code_hashes_for_delegate_call" yaml:"whitelisted_cw_code_hashes_for_delegate_call"`
	DeliverTxHookWasmGasLimit              uint64                                               `protobuf:"varint,9,opt,name=deliver_tx_hook_wasm_gas_limit,json=deliverTxHookWasmGasLimit,proto3" json:"deliver_tx_hook_wasm_gas_limit,omitempty"`
	MaxDynamicBaseFeeUpwardAdjustment      github_com_sidiora_labs_paxeer_network_sdk_types.Dec `protobuf:"bytes,10,opt,name=max_dynamic_base_fee_upward_adjustment,json=maxDynamicBaseFeeUpwardAdjustment,proto3,customtype=github.com/sidiora-labs/paxeer-network/sdk/types.Dec" json:"max_dynamic_base_fee_upward_adjustment" yaml:"max_dynamic_base_fee_upward_adjustment"`
	MaxDynamicBaseFeeDownwardAdjustment    github_com_sidiora_labs_paxeer_network_sdk_types.Dec `protobuf:"bytes,11,opt,name=max_dynamic_base_fee_downward_adjustment,json=maxDynamicBaseFeeDownwardAdjustment,proto3,customtype=github.com/sidiora-labs/paxeer-network/sdk/types.Dec" json:"max_dynamic_base_fee_downward_adjustment" yaml:"max_dynamic_base_fee_downward_adjustment"`
	TargetGasUsedPerBlock                  uint64                                               `protobuf:"varint,12,opt,name=target_gas_used_per_block,json=targetGasUsedPerBlock,proto3" json:"target_gas_used_per_block,omitempty"`
}

func (m *ParamsPreV601) Reset()      { *m = ParamsPreV601{} }
func (*ParamsPreV601) ProtoMessage() {}
func (*ParamsPreV601) Descriptor() ([]byte, []int) {
	return fileDescriptor_9272f3679901ea94, []int{3}
}
func (m *ParamsPreV601) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ParamsPreV601) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ParamsPreV601.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ParamsPreV601) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParamsPreV601.Merge(m, src)
}
func (m *ParamsPreV601) XXX_Size() int {
	return m.Size()
}
func (m *ParamsPreV601) XXX_DiscardUnknown() {
	xxx_messageInfo_ParamsPreV601.DiscardUnknown(m)
}

var xxx_messageInfo_ParamsPreV601 proto.InternalMessageInfo

func (m *ParamsPreV601) GetWhitelistedCwCodeHashesForDelegateCall() [][]byte {
	if m != nil {
		return m.WhitelistedCwCodeHashesForDelegateCall
	}
	return nil
}

func (m *ParamsPreV601) GetDeliverTxHookWasmGasLimit() uint64 {
	if m != nil {
		return m.DeliverTxHookWasmGasLimit
	}
	return 0
}

func (m *ParamsPreV601) GetTargetGasUsedPerBlock() uint64 {
	if m != nil {
		return m.TargetGasUsedPerBlock
	}
	return 0
}

type ParamsPreV606 struct {
	// string base_denom = 1 [
	//
	//	(gogoproto.moretags)   = "yaml:\"base_denom\"",
	//	(gogoproto.jsontag) = "base_denom"
	//
	// ];
	PriorityNormalizer github_com_sidiora_labs_paxeer_network_sdk_types.Dec `protobuf:"bytes,2,opt,name=priority_normalizer,json=priorityNormalizer,proto3,customtype=github.com/sidiora-labs/paxeer-network/sdk/types.Dec" json:"priority_normalizer" yaml:"priority_normalizer"`
	BaseFeePerGas      github_com_sidiora_labs_paxeer_network_sdk_types.Dec `protobuf:"bytes,3,opt,name=base_fee_per_gas,json=baseFeePerGas,proto3,customtype=github.com/sidiora-labs/paxeer-network/sdk/types.Dec" json:"base_fee_per_gas" yaml:"base_fee_per_gas"`
	MinimumFeePerGas   github_com_sidiora_labs_paxeer_network_sdk_types.Dec `protobuf:"bytes,4,opt,name=minimum_fee_per_gas,json=minimumFeePerGas,proto3,customtype=github.com/sidiora-labs/paxeer-network/sdk/types.Dec" json:"minimum_fee_per_gas" yaml:"minimum_fee_per_gas"`
	// ChainConfig chain_config = 5 [(gogoproto.moretags) = "yaml:\"chain_config\"", (gogoproto.nullable) = false];
	//
	//	string chain_id = 6 [
	//	(gogoproto.moretags)   = "yaml:\"chain_id\"",
	//	(gogoproto.customtype) = "github.com/sidiora-labs/paxeer-network/sdk/types.Int",
	//	(gogoproto.nullable)   = false,
	//	(gogoproto.jsontag) = "chain_id"
	//
	// ];
	// repeated string whitelisted_codehashes_bank_send = 7 [
	//
	//	(gogoproto.moretags)   = "yaml:\"whitelisted_codehashes_bank_send\"",
	//	(gogoproto.jsontag) = "whitelisted_codehashes_bank_send"
	//
	// ];
	WhitelistedCwCodeHashesForDelegateCall [][]byte                                             `protobuf:"bytes,8,rep,name=whitelisted_cw_code_hashes_for_delegate_call,json=whitelistedCwCodeHashesForDelegateCall,proto3" json:"whitelisted_cw_code_hashes_for_delegate_call" yaml:"whitelisted_cw_code_hashes_for_delegate_call"`
	DeliverTxHookWasmGasLimit              uint64                                               `protobuf:"varint,9,opt,name=deliver_tx_hook_wasm_gas_limit,json=deliverTxHookWasmGasLimit,proto3" json:"deliver_tx_hook_wasm_gas_limit,omitempty"`
	MaxDynamicBaseFeeUpwardAdjustment      github_com_sidiora_labs_paxeer_network_sdk_types.Dec `protobuf:"bytes,10,opt,name=max_dynamic_base_fee_upward_adjustment,json=maxDynamicBaseFeeUpwardAdjustment,proto3,customtype=github.com/sidiora-labs/paxeer-network/sdk/types.Dec" json:"max_dynamic_base_fee_upward_adjustment" yaml:"max_dynamic_base_fee_upward_adjustment"`
	MaxDynamicBaseFeeDownwardAdjustment    github_com_sidiora_labs_paxeer_network_sdk_types.Dec `protobuf:"bytes,11,opt,name=max_dynamic_base_fee_downward_adjustment,json=maxDynamicBaseFeeDownwardAdjustment,proto3,customtype=github.com/sidiora-labs/paxeer-network/sdk/types.Dec" json:"max_dynamic_base_fee_downward_adjustment" yaml:"max_dynamic_base_fee_downward_adjustment"`
	TargetGasUsedPerBlock                  uint64                                               `protobuf:"varint,12,opt,name=target_gas_used_per_block,json=targetGasUsedPerBlock,proto3" json:"target_gas_used_per_block,omitempty"`
	MaximumFeePerGas                       github_com_sidiora_labs_paxeer_network_sdk_types.Dec `protobuf:"bytes,13,opt,name=maximum_fee_per_gas,json=maximumFeePerGas,proto3,customtype=github.com/sidiora-labs/paxeer-network/sdk/types.Dec" json:"maximum_fee_per_gas" yaml:"maximum_fee_per_gas"`
}

func (m *ParamsPreV606) Reset()      { *m = ParamsPreV606{} }
func (*ParamsPreV606) ProtoMessage() {}
func (*ParamsPreV606) Descriptor() ([]byte, []int) {
	return fileDescriptor_9272f3679901ea94, []int{4}
}
func (m *ParamsPreV606) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ParamsPreV606) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ParamsPreV606.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ParamsPreV606) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParamsPreV606.Merge(m, src)
}
func (m *ParamsPreV606) XXX_Size() int {
	return m.Size()
}
func (m *ParamsPreV606) XXX_DiscardUnknown() {
	xxx_messageInfo_ParamsPreV606.DiscardUnknown(m)
}

var xxx_messageInfo_ParamsPreV606 proto.InternalMessageInfo

func (m *ParamsPreV606) GetWhitelistedCwCodeHashesForDelegateCall() [][]byte {
	if m != nil {
		return m.WhitelistedCwCodeHashesForDelegateCall
	}
	return nil
}

func (m *ParamsPreV606) GetDeliverTxHookWasmGasLimit() uint64 {
	if m != nil {
		return m.DeliverTxHookWasmGasLimit
	}
	return 0
}

func (m *ParamsPreV606) GetTargetGasUsedPerBlock() uint64 {
	if m != nil {
		return m.TargetGasUsedPerBlock
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "paxprotocol.paxchain.evm.Params")
	proto.RegisterType((*ParamsPreV580)(nil), "paxprotocol.paxchain.evm.ParamsPreV580")
	proto.RegisterType((*ParamsPreV600)(nil), "paxprotocol.paxchain.evm.ParamsPreV600")
	proto.RegisterType((*ParamsPreV601)(nil), "paxprotocol.paxchain.evm.ParamsPreV601")
	proto.RegisterType((*ParamsPreV606)(nil), "paxprotocol.paxchain.evm.ParamsPreV606")
}

func init() { proto.RegisterFile("evm/params.proto", fileDescriptor_9272f3679901ea94) }

var fileDescriptor_9272f3679901ea94 = []byte{
	// 835 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0xcf, 0x6f, 0xe3, 0x44,
	0x14, 0x8e, 0xd9, 0xee, 0x6a, 0xd7, 0xdb, 0x42, 0xe5, 0x05, 0xd6, 0xed, 0x21, 0x0e, 0x46, 0x5a,
	0xe5, 0x40, 0xe3, 0xb0, 0x0b, 0xab, 0xaa, 0xb7, 0xa6, 0x61, 0xbb, 0x07, 0x84, 0x22, 0x2f, 0x05,
	0x89, 0xcb, 0x68, 0xe2, 0x79, 0x75, 0x86, 0x78, 0x3c, 0x66, 0xc6, 0x49, 0x1c, 0x24, 0xfe, 0x07,
	0x0e, 0x48, 0x20, 0x21, 0xa4, 0x8a, 0xbf, 0x83, 0x03, 0x17, 0xa4, 0x1e, 0x7b, 0x44, 0x1c, 0x2c,
	0xd4, 0xde, 0xca, 0x2d, 0x70, 0x07, 0xf9, 0x47, 0x7f, 0xa4, 0x49, 0x69, 0xaa, 0xf6, 0x00, 0x5d,
	0x9f, 0x12, 0xcd, 0xf7, 0xcd, 0x9b, 0xf7, 0xde, 0xbc, 0xef, 0x8d, 0x67, 0xd4, 0x45, 0xe8, 0x33,
	0x2b, 0xc0, 0x02, 0x33, 0x59, 0x0b, 0x04, 0x0f, 0xb9, 0xa6, 0x07, 0x38, 0x4a, 0xff, 0x39, 0xdc,
	0xab, 0x05, 0x38, 0x72, 0x3a, 0x98, 0xfa, 0x35, 0xe8, 0xb3, 0xe5, 0xd7, 0x5d, 0xee, 0xf2, 0x14,
	0xb2, 0x92, 0x7f, 0x19, 0xdf, 0xfc, 0x6b, 0x5e, 0xbd, 0xd3, 0x4a, 0x0d, 0x68, 0x3f, 0x2a, 0xea,
	0x83, 0x40, 0x50, 0x2e, 0x68, 0x38, 0x44, 0x3e, 0x17, 0x0c, 0x7b, 0xf4, 0x4b, 0x10, 0xfa, 0x2b,
	0x15, 0xa5, 0x7a, 0xaf, 0xf1, 0xc5, 0x6e, 0x6c, 0x94, 0x7e, 0x8b, 0x8d, 0xf7, 0x5c, 0x1a, 0x76,
	0x7a, 0xed, 0x9a, 0xc3, 0x99, 0x25, 0x29, 0xa1, 0x5c, 0xe0, 0x15, 0x0f, 0xb7, 0xa5, 0x15, 0xe0,
	0x08, 0x40, 0xac, 0xf8, 0x10, 0x0e, 0xb8, 0xe8, 0x5a, 0x92, 0x74, 0xad, 0x70, 0x18, 0x80, 0xac,
	0x35, 0xc1, 0x39, 0x8c, 0x8d, 0x69, 0xa6, 0x47, 0xb1, 0xb1, 0x3c, 0xc4, 0xcc, 0x5b, 0x33, 0xa7,
	0x80, 0xa6, 0xad, 0x1d, 0x8d, 0x7e, 0x74, 0x3c, 0xa8, 0x7d, 0xa3, 0xa8, 0x8b, 0x6d, 0x2c, 0x01,
	0x6d, 0x03, 0xa0, 0x00, 0x04, 0x72, 0xb1, 0xd4, 0x6f, 0xa5, 0x1e, 0x76, 0xaf, 0xe8, 0xe1, 0x84,
	0xdd, 0x51, 0x6c, 0x3c, 0xcc, 0xdc, 0x3b, 0x8b, 0x98, 0xf6, 0x42, 0x32, 0xf4, 0x0c, 0xa0, 0x05,
	0x62, 0x13, 0x4b, 0x6d, 0x47, 0x51, 0x1f, 0x30, 0xea, 0x53, 0xd6, 0x63, 0x63, 0x9e, 0xcd, 0x5d,
	0x4f, 0xee, 0xa6, 0x98, 0x3e, 0xc9, 0xdd, 0x14, 0xd0, 0xb4, 0x17, 0xf3, 0xd1, 0x13, 0x17, 0x7f,
	0x51, 0xd4, 0x77, 0x06, 0x1d, 0x1a, 0x82, 0x47, 0x65, 0x08, 0x04, 0x39, 0x03, 0xe4, 0x70, 0x02,
	0xa8, 0x83, 0x65, 0x07, 0x24, 0xda, 0xe6, 0x02, 0x11, 0xf0, 0xc0, 0xc5, 0x21, 0x20, 0x07, 0x7b,
	0x9e, 0x7e, 0xb7, 0x72, 0xab, 0x3a, 0xdf, 0x70, 0x0f, 0x63, 0xe3, 0x52, 0xf3, 0x46, 0xb1, 0xf1,
	0x24, 0x73, 0xec, 0x32, 0xb3, 0x4c, 0xfb, 0xd1, 0x29, 0xfa, 0xc6, 0x60, 0x83, 0x13, 0x78, 0x9e,
	0x72, 0x9f, 0x71, 0xd1, 0xcc, 0x99, 0x1b, 0xd8, 0xf3, 0xb4, 0x75, 0xb5, 0x4c, 0xc0, 0xa3, 0x7d,
	0x10, 0x28, 0x8c, 0x50, 0x87, 0xf3, 0x2e, 0x1a, 0x60, 0xc9, 0x92, 0xb0, 0x91, 0x47, 0x19, 0x0d,
	0xf5, 0x7b, 0x15, 0xa5, 0x3a, 0x67, 0x2f, 0xe5, 0xac, 0x8f, 0xa3, 0xe7, 0x9c, 0x77, 0x3f, 0xc5,
	0x92, 0x6d, 0x62, 0xf9, 0x61, 0x42, 0xd0, 0xfe, 0x50, 0xd4, 0x47, 0x0c, 0x47, 0x88, 0x0c, 0x7d,
	0xcc, 0xa8, 0x83, 0x8e, 0xb7, 0xb7, 0x17, 0x0c, 0xb0, 0x20, 0x08, 0x93, 0xcf, 0x7b, 0x32, 0x64,
	0xe0, 0x87, 0xba, 0x9a, 0x6e, 0xe0, 0xb7, 0xca, 0x15, 0x77, 0x70, 0xc6, 0xe5, 0x46, 0xb1, 0xb1,
	0x92, 0x6f, 0xea, 0x4c, 0x7c, 0xd3, 0x7e, 0x8b, 0xe1, 0xa8, 0x99, 0xf1, 0x1a, 0x59, 0x45, 0x6e,
	0xa5, 0xa4, 0xf5, 0x63, 0x8e, 0xf6, 0xa7, 0xa2, 0x56, 0xa7, 0x9a, 0x23, 0x7c, 0xe0, 0x9f, 0x8d,
	0xf7, 0x7e, 0x1a, 0xef, 0xf7, 0x57, 0x8d, 0x77, 0xe6, 0x05, 0x47, 0xb1, 0x61, 0xfd, 0x4b, 0xc4,
	0x53, 0x66, 0x98, 0xf6, 0xdb, 0x13, 0x31, 0x37, 0x73, 0xda, 0xa9, 0xa8, 0x57, 0xd5, 0xa5, 0x10,
	0x0b, 0x17, 0xc2, 0xb4, 0x30, 0x7a, 0x12, 0x48, 0x2a, 0x8e, 0xb6, 0xc7, 0x9d, 0xae, 0x3e, 0x9f,
	0x56, 0xc8, 0x1b, 0x19, 0x61, 0x13, 0xcb, 0x2d, 0x09, 0xa4, 0x05, 0xa2, 0x91, 0x80, 0x99, 0x96,
	0x71, 0x34, 0xa1, 0xe5, 0x85, 0x6b, 0xd2, 0xf2, 0xa4, 0xe9, 0x53, 0x5a, 0x9e, 0x04, 0x13, 0x2d,
	0x67, 0xa3, 0x27, 0x5a, 0xfe, 0x4a, 0x5d, 0x12, 0xe0, 0x26, 0x52, 0x11, 0x28, 0xe0, 0xd4, 0x4f,
	0x7e, 0x09, 0x95, 0xb8, 0xed, 0x01, 0xd1, 0x5f, 0xad, 0x28, 0xd5, 0xbb, 0x8d, 0xf5, 0xc3, 0xd8,
	0x38, 0x9f, 0x34, 0x8a, 0x8d, 0x4a, 0xb6, 0xe2, 0xb9, 0x14, 0xd3, 0x7e, 0x78, 0x84, 0xb5, 0x32,
	0xa8, 0x99, 0x23, 0xda, 0x9a, 0xba, 0x1c, 0xe0, 0x08, 0x49, 0x19, 0x72, 0x01, 0x48, 0xe6, 0x39,
	0x06, 0x1a, 0x3c, 0x7e, 0x5c, 0xaf, 0xeb, 0xaf, 0xa5, 0xc9, 0x7d, 0x33, 0xc0, 0xd1, 0x8b, 0x94,
	0xf0, 0x22, 0x4d, 0xf1, 0x07, 0x19, 0xba, 0x36, 0xf7, 0xdd, 0x8e, 0x51, 0x32, 0x7f, 0xba, 0xad,
	0x2e, 0x64, 0xc7, 0x4e, 0x4b, 0xc0, 0x27, 0xef, 0xaf, 0xd6, 0x8b, 0xd3, 0xa7, 0x38, 0x7d, 0xfe,
	0x07, 0xa7, 0x4f, 0x5e, 0xbe, 0x7f, 0x8f, 0x95, 0xef, 0xd3, 0x7a, 0x51, 0xbe, 0x37, 0xbc, 0x7c,
	0x2f, 0xfe, 0xe8, 0xb8, 0x7d, 0xd1, 0x47, 0xc7, 0xcd, 0x52, 0xc0, 0x0f, 0xea, 0xb8, 0x02, 0xde,
	0x2d, 0x14, 0x50, 0x34, 0xf0, 0xe2, 0xfa, 0x50, 0x5c, 0x1f, 0x5e, 0xf6, 0xeb, 0x43, 0xde, 0x1f,
	0x7f, 0xbe, 0x3f, 0xde, 0x1f, 0x9f, 0x16, 0xfd, 0xb1, 0xe8, 0x8f, 0x45, 0x7f, 0x2c, 0xfa, 0x63,
	0xf1, 0xbc, 0xf2, 0x9f, 0x7f, 0x5e, 0xc9, 0x5a, 0x78, 0xc3, 0xde, 0xdd, 0x2f, 0x2b, 0x7b, 0xfb,
	0x65, 0xe5, 0xf7, 0xfd, 0xb2, 0xf2, 0xf5, 0x41, 0xb9, 0xb4, 0x77, 0x50, 0x2e, 0xfd, 0x7a, 0x50,
	0x2e, 0x7d, 0xb6, 0x3a, 0xa3, 0x73, 0x8c, 0x93, 0x9e, 0x07, 0xd2, 0x82, 0x3e, 0xcb, 0x9c, 0x6c,
	0xdf, 0x49, 0x5f, 0xdd, 0x9f, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x65, 0x0a, 0x54, 0xb9,
	0x17, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PaxSstoreSetGasEip2200 != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.PaxSstoreSetGasEip2200))
		i--
		dAtA[i] = 0x78
	}
	if m.RegisterPointerDisabled {
		i--
		if m.RegisterPointerDisabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x70
	}
	{
		size := m.MaximumFeePerGas.Size()
		i -= size
		if _, err := m.MaximumFeePerGas.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x6a
	if m.TargetGasUsedPerBlock != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.TargetGasUsedPerBlock))
		i--
		dAtA[i] = 0x60
	}
	{
		size := m.MaxDynamicBaseFeeDownwardAdjustment.Size()
		i -= size
		if _, err := m.MaxDynamicBaseFeeDownwardAdjustment.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x5a
	{
		size := m.MaxDynamicBaseFeeUpwardAdjustment.Size()
		i -= size
		if _, err := m.MaxDynamicBaseFeeUpwardAdjustment.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	if m.DeliverTxHookWasmGasLimit != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DeliverTxHookWasmGasLimit))
		i--
		dAtA[i] = 0x48
	}
	if len(m.WhitelistedCwCodeHashesForDelegateCall) > 0 {
		for iNdEx := len(m.WhitelistedCwCodeHashesForDelegateCall) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.WhitelistedCwCodeHashesForDelegateCall[iNdEx])
			copy(dAtA[i:], m.WhitelistedCwCodeHashesForDelegateCall[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.WhitelistedCwCodeHashesForDelegateCall[iNdEx])))
			i--
			dAtA[i] = 0x42
		}
	}
	{
		size := m.MinimumFeePerGas.Size()
		i -= size
		if _, err := m.MinimumFeePerGas.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.BaseFeePerGas.Size()
		i -= size
		if _, err := m.BaseFeePerGas.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.PriorityNormalizer.Size()
		i -= size
		if _, err := m.PriorityNormalizer.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	return len(dAtA) - i, nil
}

func (m *ParamsPreV580) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ParamsPreV580) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ParamsPreV580) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.WhitelistedCwCodeHashesForDelegateCall) > 0 {
		for iNdEx := len(m.WhitelistedCwCodeHashesForDelegateCall) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.WhitelistedCwCodeHashesForDelegateCall[iNdEx])
			copy(dAtA[i:], m.WhitelistedCwCodeHashesForDelegateCall[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.WhitelistedCwCodeHashesForDelegateCall[iNdEx])))
			i--
			dAtA[i] = 0x42
		}
	}
	{
		size := m.MinimumFeePerGas.Size()
		i -= size
		if _, err := m.MinimumFeePerGas.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.BaseFeePerGas.Size()
		i -= size
		if _, err := m.BaseFeePerGas.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.PriorityNormalizer.Size()
		i -= size
		if _, err := m.PriorityNormalizer.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	return len(dAtA) - i, nil
}

func (m *ParamsPreV600) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ParamsPreV600) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ParamsPreV600) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.WhitelistedCwCodeHashesForDelegateCall) > 0 {
		for iNdEx := len(m.WhitelistedCwCodeHashesForDelegateCall) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.WhitelistedCwCodeHashesForDelegateCall[iNdEx])
			copy(dAtA[i:], m.WhitelistedCwCodeHashesForDelegateCall[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.WhitelistedCwCodeHashesForDelegateCall[iNdEx])))
			i--
			dAtA[i] = 0x42
		}
	}
	if m.DeliverTxHookWasmGasLimit != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DeliverTxHookWasmGasLimit))
		i--
		dAtA[i] = 0x28
	}
	{
		size := m.MinimumFeePerGas.Size()
		i -= size
		if _, err := m.MinimumFeePerGas.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.BaseFeePerGas.Size()
		i -= size
		if _, err := m.BaseFeePerGas.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.PriorityNormalizer.Size()
		i -= size
		if _, err := m.PriorityNormalizer.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	return len(dAtA) - i, nil
}

func (m *ParamsPreV601) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ParamsPreV601) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ParamsPreV601) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TargetGasUsedPerBlock != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.TargetGasUsedPerBlock))
		i--
		dAtA[i] = 0x60
	}
	{
		size := m.MaxDynamicBaseFeeDownwardAdjustment.Size()
		i -= size
		if _, err := m.MaxDynamicBaseFeeDownwardAdjustment.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x5a
	{
		size := m.MaxDynamicBaseFeeUpwardAdjustment.Size()
		i -= size
		if _, err := m.MaxDynamicBaseFeeUpwardAdjustment.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	if m.DeliverTxHookWasmGasLimit != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DeliverTxHookWasmGasLimit))
		i--
		dAtA[i] = 0x48
	}
	if len(m.WhitelistedCwCodeHashesForDelegateCall) > 0 {
		for iNdEx := len(m.WhitelistedCwCodeHashesForDelegateCall) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.WhitelistedCwCodeHashesForDelegateCall[iNdEx])
			copy(dAtA[i:], m.WhitelistedCwCodeHashesForDelegateCall[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.WhitelistedCwCodeHashesForDelegateCall[iNdEx])))
			i--
			dAtA[i] = 0x42
		}
	}
	{
		size := m.MinimumFeePerGas.Size()
		i -= size
		if _, err := m.MinimumFeePerGas.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.BaseFeePerGas.Size()
		i -= size
		if _, err := m.BaseFeePerGas.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.PriorityNormalizer.Size()
		i -= size
		if _, err := m.PriorityNormalizer.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	return len(dAtA) - i, nil
}

func (m *ParamsPreV606) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ParamsPreV606) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ParamsPreV606) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.MaximumFeePerGas.Size()
		i -= size
		if _, err := m.MaximumFeePerGas.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x6a
	if m.TargetGasUsedPerBlock != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.TargetGasUsedPerBlock))
		i--
		dAtA[i] = 0x60
	}
	{
		size := m.MaxDynamicBaseFeeDownwardAdjustment.Size()
		i -= size
		if _, err := m.MaxDynamicBaseFeeDownwardAdjustment.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x5a
	{
		size := m.MaxDynamicBaseFeeUpwardAdjustment.Size()
		i -= size
		if _, err := m.MaxDynamicBaseFeeUpwardAdjustment.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	if m.DeliverTxHookWasmGasLimit != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DeliverTxHookWasmGasLimit))
		i--
		dAtA[i] = 0x48
	}
	if len(m.WhitelistedCwCodeHashesForDelegateCall) > 0 {
		for iNdEx := len(m.WhitelistedCwCodeHashesForDelegateCall) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.WhitelistedCwCodeHashesForDelegateCall[iNdEx])
			copy(dAtA[i:], m.WhitelistedCwCodeHashesForDelegateCall[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.WhitelistedCwCodeHashesForDelegateCall[iNdEx])))
			i--
			dAtA[i] = 0x42
		}
	}
	{
		size := m.MinimumFeePerGas.Size()
		i -= size
		if _, err := m.MinimumFeePerGas.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.BaseFeePerGas.Size()
		i -= size
		if _, err := m.BaseFeePerGas.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.PriorityNormalizer.Size()
		i -= size
		if _, err := m.PriorityNormalizer.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.PriorityNormalizer.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.BaseFeePerGas.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MinimumFeePerGas.Size()
	n += 1 + l + sovParams(uint64(l))
	if len(m.WhitelistedCwCodeHashesForDelegateCall) > 0 {
		for _, b := range m.WhitelistedCwCodeHashesForDelegateCall {
			l = len(b)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if m.DeliverTxHookWasmGasLimit != 0 {
		n += 1 + sovParams(uint64(m.DeliverTxHookWasmGasLimit))
	}
	l = m.MaxDynamicBaseFeeUpwardAdjustment.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MaxDynamicBaseFeeDownwardAdjustment.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.TargetGasUsedPerBlock != 0 {
		n += 1 + sovParams(uint64(m.TargetGasUsedPerBlock))
	}
	l = m.MaximumFeePerGas.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.RegisterPointerDisabled {
		n += 2
	}
	if m.PaxSstoreSetGasEip2200 != 0 {
		n += 1 + sovParams(uint64(m.PaxSstoreSetGasEip2200))
	}
	return n
}

func (m *ParamsPreV580) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.PriorityNormalizer.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.BaseFeePerGas.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MinimumFeePerGas.Size()
	n += 1 + l + sovParams(uint64(l))
	if len(m.WhitelistedCwCodeHashesForDelegateCall) > 0 {
		for _, b := range m.WhitelistedCwCodeHashesForDelegateCall {
			l = len(b)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func (m *ParamsPreV600) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.PriorityNormalizer.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.BaseFeePerGas.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MinimumFeePerGas.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.DeliverTxHookWasmGasLimit != 0 {
		n += 1 + sovParams(uint64(m.DeliverTxHookWasmGasLimit))
	}
	if len(m.WhitelistedCwCodeHashesForDelegateCall) > 0 {
		for _, b := range m.WhitelistedCwCodeHashesForDelegateCall {
			l = len(b)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func (m *ParamsPreV601) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.PriorityNormalizer.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.BaseFeePerGas.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MinimumFeePerGas.Size()
	n += 1 + l + sovParams(uint64(l))
	if len(m.WhitelistedCwCodeHashesForDelegateCall) > 0 {
		for _, b := range m.WhitelistedCwCodeHashesForDelegateCall {
			l = len(b)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if m.DeliverTxHookWasmGasLimit != 0 {
		n += 1 + sovParams(uint64(m.DeliverTxHookWasmGasLimit))
	}
	l = m.MaxDynamicBaseFeeUpwardAdjustment.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MaxDynamicBaseFeeDownwardAdjustment.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.TargetGasUsedPerBlock != 0 {
		n += 1 + sovParams(uint64(m.TargetGasUsedPerBlock))
	}
	return n
}

func (m *ParamsPreV606) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.PriorityNormalizer.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.BaseFeePerGas.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MinimumFeePerGas.Size()
	n += 1 + l + sovParams(uint64(l))
	if len(m.WhitelistedCwCodeHashesForDelegateCall) > 0 {
		for _, b := range m.WhitelistedCwCodeHashesForDelegateCall {
			l = len(b)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if m.DeliverTxHookWasmGasLimit != 0 {
		n += 1 + sovParams(uint64(m.DeliverTxHookWasmGasLimit))
	}
	l = m.MaxDynamicBaseFeeUpwardAdjustment.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MaxDynamicBaseFeeDownwardAdjustment.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.TargetGasUsedPerBlock != 0 {
		n += 1 + sovParams(uint64(m.TargetGasUsedPerBlock))
	}
	l = m.MaximumFeePerGas.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriorityNormalizer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PriorityNormalizer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseFeePerGas", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BaseFeePerGas.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinimumFeePerGas", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinimumFeePerGas.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WhitelistedCwCodeHashesForDelegateCall", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WhitelistedCwCodeHashesForDelegateCall = append(m.WhitelistedCwCodeHashesForDelegateCall, make([]byte, postIndex-iNdEx))
			copy(m.WhitelistedCwCodeHashesForDelegateCall[len(m.WhitelistedCwCodeHashesForDelegateCall)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeliverTxHookWasmGasLimit", wireType)
			}
			m.DeliverTxHookWasmGasLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeliverTxHookWasmGasLimit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDynamicBaseFeeUpwardAdjustment", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxDynamicBaseFeeUpwardAdjustment.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDynamicBaseFeeDownwardAdjustment", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxDynamicBaseFeeDownwardAdjustment.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetGasUsedPerBlock", wireType)
			}
			m.TargetGasUsedPerBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TargetGasUsedPerBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaximumFeePerGas", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaximumFeePerGas.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisterPointerDisabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RegisterPointerDisabled = bool(v != 0)
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaxSstoreSetGasEip2200", wireType)
			}
			m.PaxSstoreSetGasEip2200 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PaxSstoreSetGasEip2200 |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ParamsPreV580) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ParamsPreV580: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ParamsPreV580: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriorityNormalizer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PriorityNormalizer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseFeePerGas", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BaseFeePerGas.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinimumFeePerGas", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinimumFeePerGas.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WhitelistedCwCodeHashesForDelegateCall", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WhitelistedCwCodeHashesForDelegateCall = append(m.WhitelistedCwCodeHashesForDelegateCall, make([]byte, postIndex-iNdEx))
			copy(m.WhitelistedCwCodeHashesForDelegateCall[len(m.WhitelistedCwCodeHashesForDelegateCall)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ParamsPreV600) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ParamsPreV600: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ParamsPreV600: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriorityNormalizer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PriorityNormalizer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseFeePerGas", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BaseFeePerGas.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinimumFeePerGas", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinimumFeePerGas.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeliverTxHookWasmGasLimit", wireType)
			}
			m.DeliverTxHookWasmGasLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeliverTxHookWasmGasLimit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WhitelistedCwCodeHashesForDelegateCall", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WhitelistedCwCodeHashesForDelegateCall = append(m.WhitelistedCwCodeHashesForDelegateCall, make([]byte, postIndex-iNdEx))
			copy(m.WhitelistedCwCodeHashesForDelegateCall[len(m.WhitelistedCwCodeHashesForDelegateCall)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ParamsPreV601) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ParamsPreV601: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ParamsPreV601: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriorityNormalizer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PriorityNormalizer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseFeePerGas", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BaseFeePerGas.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinimumFeePerGas", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinimumFeePerGas.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WhitelistedCwCodeHashesForDelegateCall", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WhitelistedCwCodeHashesForDelegateCall = append(m.WhitelistedCwCodeHashesForDelegateCall, make([]byte, postIndex-iNdEx))
			copy(m.WhitelistedCwCodeHashesForDelegateCall[len(m.WhitelistedCwCodeHashesForDelegateCall)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeliverTxHookWasmGasLimit", wireType)
			}
			m.DeliverTxHookWasmGasLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeliverTxHookWasmGasLimit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDynamicBaseFeeUpwardAdjustment", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxDynamicBaseFeeUpwardAdjustment.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDynamicBaseFeeDownwardAdjustment", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxDynamicBaseFeeDownwardAdjustment.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetGasUsedPerBlock", wireType)
			}
			m.TargetGasUsedPerBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TargetGasUsedPerBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ParamsPreV606) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ParamsPreV606: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ParamsPreV606: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriorityNormalizer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PriorityNormalizer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseFeePerGas", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BaseFeePerGas.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinimumFeePerGas", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinimumFeePerGas.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WhitelistedCwCodeHashesForDelegateCall", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WhitelistedCwCodeHashesForDelegateCall = append(m.WhitelistedCwCodeHashesForDelegateCall, make([]byte, postIndex-iNdEx))
			copy(m.WhitelistedCwCodeHashesForDelegateCall[len(m.WhitelistedCwCodeHashesForDelegateCall)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeliverTxHookWasmGasLimit", wireType)
			}
			m.DeliverTxHookWasmGasLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeliverTxHookWasmGasLimit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDynamicBaseFeeUpwardAdjustment", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxDynamicBaseFeeUpwardAdjustment.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDynamicBaseFeeDownwardAdjustment", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxDynamicBaseFeeDownwardAdjustment.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetGasUsedPerBlock", wireType)
			}
			m.TargetGasUsedPerBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TargetGasUsedPerBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaximumFeePerGas", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaximumFeePerGas.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
