// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: evm/query.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryPaxAddressByEVMAddressRequest struct {
	EvmAddress string `protobuf:"bytes,1,opt,name=evm_address,json=evmAddress,proto3" json:"evm_address,omitempty"`
}

func (m *QueryPaxAddressByEVMAddressRequest) Reset()         { *m = QueryPaxAddressByEVMAddressRequest{} }
func (m *QueryPaxAddressByEVMAddressRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPaxAddressByEVMAddressRequest) ProtoMessage()    {}
func (*QueryPaxAddressByEVMAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11c0d37eed5339f7, []int{0}
}
func (m *QueryPaxAddressByEVMAddressRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPaxAddressByEVMAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPaxAddressByEVMAddressRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPaxAddressByEVMAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPaxAddressByEVMAddressRequest.Merge(m, src)
}
func (m *QueryPaxAddressByEVMAddressRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPaxAddressByEVMAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPaxAddressByEVMAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPaxAddressByEVMAddressRequest proto.InternalMessageInfo

func (m *QueryPaxAddressByEVMAddressRequest) GetEvmAddress() string {
	if m != nil {
		return m.EvmAddress
	}
	return ""
}

type QueryPaxAddressByEVMAddressResponse struct {
	PaxAddress string `protobuf:"bytes,1,opt,name=pax_address,json=paxAddress,proto3" json:"pax_address,omitempty"`
	Associated bool   `protobuf:"varint,2,opt,name=associated,proto3" json:"associated,omitempty"`
}

func (m *QueryPaxAddressByEVMAddressResponse) Reset()         { *m = QueryPaxAddressByEVMAddressResponse{} }
func (m *QueryPaxAddressByEVMAddressResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPaxAddressByEVMAddressResponse) ProtoMessage()    {}
func (*QueryPaxAddressByEVMAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_11c0d37eed5339f7, []int{1}
}
func (m *QueryPaxAddressByEVMAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPaxAddressByEVMAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPaxAddressByEVMAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPaxAddressByEVMAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPaxAddressByEVMAddressResponse.Merge(m, src)
}
func (m *QueryPaxAddressByEVMAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPaxAddressByEVMAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPaxAddressByEVMAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPaxAddressByEVMAddressResponse proto.InternalMessageInfo

func (m *QueryPaxAddressByEVMAddressResponse) GetPaxAddress() string {
	if m != nil {
		return m.PaxAddress
	}
	return ""
}

func (m *QueryPaxAddressByEVMAddressResponse) GetAssociated() bool {
	if m != nil {
		return m.Associated
	}
	return false
}

type QueryEVMAddressByPaxAddressRequest struct {
	PaxAddress string `protobuf:"bytes,1,opt,name=pax_address,json=paxAddress,proto3" json:"pax_address,omitempty"`
}

func (m *QueryEVMAddressByPaxAddressRequest) Reset()         { *m = QueryEVMAddressByPaxAddressRequest{} }
func (m *QueryEVMAddressByPaxAddressRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEVMAddressByPaxAddressRequest) ProtoMessage()    {}
func (*QueryEVMAddressByPaxAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11c0d37eed5339f7, []int{2}
}
func (m *QueryEVMAddressByPaxAddressRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEVMAddressByPaxAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEVMAddressByPaxAddressRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEVMAddressByPaxAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEVMAddressByPaxAddressRequest.Merge(m, src)
}
func (m *QueryEVMAddressByPaxAddressRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEVMAddressByPaxAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEVMAddressByPaxAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEVMAddressByPaxAddressRequest proto.InternalMessageInfo

func (m *QueryEVMAddressByPaxAddressRequest) GetPaxAddress() string {
	if m != nil {
		return m.PaxAddress
	}
	return ""
}

type QueryEVMAddressByPaxAddressResponse struct {
	EvmAddress string `protobuf:"bytes,1,opt,name=evm_address,json=evmAddress,proto3" json:"evm_address,omitempty"`
	Associated bool   `protobuf:"varint,2,opt,name=associated,proto3" json:"associated,omitempty"`
}

func (m *QueryEVMAddressByPaxAddressResponse) Reset()         { *m = QueryEVMAddressByPaxAddressResponse{} }
func (m *QueryEVMAddressByPaxAddressResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEVMAddressByPaxAddressResponse) ProtoMessage()    {}
func (*QueryEVMAddressByPaxAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_11c0d37eed5339f7, []int{3}
}
func (m *QueryEVMAddressByPaxAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEVMAddressByPaxAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEVMAddressByPaxAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEVMAddressByPaxAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEVMAddressByPaxAddressResponse.Merge(m, src)
}
func (m *QueryEVMAddressByPaxAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEVMAddressByPaxAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEVMAddressByPaxAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEVMAddressByPaxAddressResponse proto.InternalMessageInfo

func (m *QueryEVMAddressByPaxAddressResponse) GetEvmAddress() string {
	if m != nil {
		return m.EvmAddress
	}
	return ""
}

func (m *QueryEVMAddressByPaxAddressResponse) GetAssociated() bool {
	if m != nil {
		return m.Associated
	}
	return false
}

type QueryStaticCallRequest struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	To   string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
}

func (m *QueryStaticCallRequest) Reset()         { *m = QueryStaticCallRequest{} }
func (m *QueryStaticCallRequest) String() string { return proto.CompactTextString(m) }
func (*QueryStaticCallRequest) ProtoMessage()    {}
func (*QueryStaticCallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11c0d37eed5339f7, []int{4}
}
func (m *QueryStaticCallRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryStaticCallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryStaticCallRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryStaticCallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStaticCallRequest.Merge(m, src)
}
func (m *QueryStaticCallRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryStaticCallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStaticCallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStaticCallRequest proto.InternalMessageInfo

func (m *QueryStaticCallRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *QueryStaticCallRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type QueryStaticCallResponse struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *QueryStaticCallResponse) Reset()         { *m = QueryStaticCallResponse{} }
func (m *QueryStaticCallResponse) String() string { return proto.CompactTextString(m) }
func (*QueryStaticCallResponse) ProtoMessage()    {}
func (*QueryStaticCallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_11c0d37eed5339f7, []int{5}
}
func (m *QueryStaticCallResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryStaticCallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryStaticCallResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryStaticCallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStaticCallResponse.Merge(m, src)
}
func (m *QueryStaticCallResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryStaticCallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStaticCallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStaticCallResponse proto.InternalMessageInfo

func (m *QueryStaticCallResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type QueryPointerRequest struct {
	PointerType PointerType `protobuf:"varint,1,opt,name=pointer_type,json=pointerType,proto3,enum=paxprotocol.paxchain.evm.PointerType" json:"pointer_type,omitempty"`
	Pointee     string      `protobuf:"bytes,2,opt,name=pointee,proto3" json:"pointee,omitempty"`
}

func (m *QueryPointerRequest) Reset()         { *m = QueryPointerRequest{} }
func (m *QueryPointerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPointerRequest) ProtoMessage()    {}
func (*QueryPointerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11c0d37eed5339f7, []int{6}
}
func (m *QueryPointerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPointerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPointerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPointerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPointerRequest.Merge(m, src)
}
func (m *QueryPointerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPointerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPointerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPointerRequest proto.InternalMessageInfo

func (m *QueryPointerRequest) GetPointerType() PointerType {
	if m != nil {
		return m.PointerType
	}
	return PointerType_ERC20
}

func (m *QueryPointerRequest) GetPointee() string {
	if m != nil {
		return m.Pointee
	}
	return ""
}

type QueryPointerResponse struct {
	Pointer string `protobuf:"bytes,1,opt,name=pointer,proto3" json:"pointer,omitempty"`
	Version uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Exists  bool   `protobuf:"varint,3,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (m *QueryPointerResponse) Reset()         { *m = QueryPointerResponse{} }
func (m *QueryPointerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPointerResponse) ProtoMessage()    {}
func (*QueryPointerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_11c0d37eed5339f7, []int{7}
}
func (m *QueryPointerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPointerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPointerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPointerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPointerResponse.Merge(m, src)
}
func (m *QueryPointerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPointerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPointerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPointerResponse proto.InternalMessageInfo

func (m *QueryPointerResponse) GetPointer() string {
	if m != nil {
		return m.Pointer
	}
	return ""
}

func (m *QueryPointerResponse) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *QueryPointerResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

type QueryPointerVersionRequest struct {
	PointerType PointerType `protobuf:"varint,1,opt,name=pointer_type,json=pointerType,proto3,enum=paxprotocol.paxchain.evm.PointerType" json:"pointer_type,omitempty"`
}

func (m *QueryPointerVersionRequest) Reset()         { *m = QueryPointerVersionRequest{} }
func (m *QueryPointerVersionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPointerVersionRequest) ProtoMessage()    {}
func (*QueryPointerVersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11c0d37eed5339f7, []int{8}
}
func (m *QueryPointerVersionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPointerVersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPointerVersionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPointerVersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPointerVersionRequest.Merge(m, src)
}
func (m *QueryPointerVersionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPointerVersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPointerVersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPointerVersionRequest proto.InternalMessageInfo

func (m *QueryPointerVersionRequest) GetPointerType() PointerType {
	if m != nil {
		return m.PointerType
	}
	return PointerType_ERC20
}

type QueryPointerVersionResponse struct {
	Version  uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	CwCodeId uint64 `protobuf:"varint,2,opt,name=cw_code_id,json=cwCodeId,proto3" json:"cw_code_id,omitempty"`
}

func (m *QueryPointerVersionResponse) Reset()         { *m = QueryPointerVersionResponse{} }
func (m *QueryPointerVersionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPointerVersionResponse) ProtoMessage()    {}
func (*QueryPointerVersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_11c0d37eed5339f7, []int{9}
}
func (m *QueryPointerVersionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPointerVersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPointerVersionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPointerVersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPointerVersionResponse.Merge(m, src)
}
func (m *QueryPointerVersionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPointerVersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPointerVersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPointerVersionResponse proto.InternalMessageInfo

func (m *QueryPointerVersionResponse) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *QueryPointerVersionResponse) GetCwCodeId() uint64 {
	if m != nil {
		return m.CwCodeId
	}
	return 0
}

type QueryPointeeRequest struct {
	PointerType PointerType `protobuf:"varint,1,opt,name=pointer_type,json=pointerType,proto3,enum=paxprotocol.paxchain.evm.PointerType" json:"pointer_type,omitempty"`
	Pointer     string      `protobuf:"bytes,2,opt,name=pointer,proto3" json:"pointer,omitempty"`
}

func (m *QueryPointeeRequest) Reset()         { *m = QueryPointeeRequest{} }
func (m *QueryPointeeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPointeeRequest) ProtoMessage()    {}
func (*QueryPointeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11c0d37eed5339f7, []int{10}
}
func (m *QueryPointeeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPointeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPointeeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPointeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPointeeRequest.Merge(m, src)
}
func (m *QueryPointeeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPointeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPointeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPointeeRequest proto.InternalMessageInfo

func (m *QueryPointeeRequest) GetPointerType() PointerType {
	if m != nil {
		return m.PointerType
	}
	return PointerType_ERC20
}

func (m *QueryPointeeRequest) GetPointer() string {
	if m != nil {
		return m.Pointer
	}
	return ""
}

type QueryPointeeResponse struct {
	Pointee string `protobuf:"bytes,1,opt,name=pointee,proto3" json:"pointee,omitempty"`
	Version uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Exists  bool   `protobuf:"varint,3,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (m *QueryPointeeResponse) Reset()         { *m = QueryPointeeResponse{} }
func (m *QueryPointeeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPointeeResponse) ProtoMessage()    {}
func (*QueryPointeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_11c0d37eed5339f7, []int{11}
}
func (m *QueryPointeeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPointeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPointeeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPointeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPointeeResponse.Merge(m, src)
}
func (m *QueryPointeeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPointeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPointeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPointeeResponse proto.InternalMessageInfo

func (m *QueryPointeeResponse) GetPointee() string {
	if m != nil {
		return m.Pointee
	}
	return ""
}

func (m *QueryPointeeResponse) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *QueryPointeeResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func init() {
	proto.RegisterType((*QueryPaxAddressByEVMAddressRequest)(nil), "paxprotocol.paxchain.evm.QueryPaxAddressByEVMAddressRequest")
	proto.RegisterType((*QueryPaxAddressByEVMAddressResponse)(nil), "paxprotocol.paxchain.evm.QueryPaxAddressByEVMAddressResponse")
	proto.RegisterType((*QueryEVMAddressByPaxAddressRequest)(nil), "paxprotocol.paxchain.evm.QueryEVMAddressByPaxAddressRequest")
	proto.RegisterType((*QueryEVMAddressByPaxAddressResponse)(nil), "paxprotocol.paxchain.evm.QueryEVMAddressByPaxAddressResponse")
	proto.RegisterType((*QueryStaticCallRequest)(nil), "paxprotocol.paxchain.evm.QueryStaticCallRequest")
	proto.RegisterType((*QueryStaticCallResponse)(nil), "paxprotocol.paxchain.evm.QueryStaticCallResponse")
	proto.RegisterType((*QueryPointerRequest)(nil), "paxprotocol.paxchain.evm.QueryPointerRequest")
	proto.RegisterType((*QueryPointerResponse)(nil), "paxprotocol.paxchain.evm.QueryPointerResponse")
	proto.RegisterType((*QueryPointerVersionRequest)(nil), "paxprotocol.paxchain.evm.QueryPointerVersionRequest")
	proto.RegisterType((*QueryPointerVersionResponse)(nil), "paxprotocol.paxchain.evm.QueryPointerVersionResponse")
	proto.RegisterType((*QueryPointeeRequest)(nil), "paxprotocol.paxchain.evm.QueryPointeeRequest")
	proto.RegisterType((*QueryPointeeResponse)(nil), "paxprotocol.paxchain.evm.QueryPointeeResponse")
}

func init() { proto.RegisterFile("evm/query.proto", fileDescriptor_11c0d37eed5339f7) }

var fileDescriptor_11c0d37eed5339f7 = []byte{
	// 684 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0x43, 0xe9, 0xcf, 0xb4, 0x14, 0x69, 0x41, 0x25, 0x32, 0x95, 0xa9, 0xcc, 0x8f, 0xaa,
	0x8a, 0xd8, 0x50, 0x40, 0xe2, 0x50, 0x0e, 0xb4, 0xaa, 0x04, 0x07, 0x24, 0x30, 0xd0, 0x03, 0x97,
	0x68, 0x63, 0x4f, 0x5b, 0x8b, 0xd8, 0xeb, 0x7a, 0x37, 0x69, 0x72, 0xe5, 0x09, 0x90, 0xe0, 0xca,
	0x81, 0x47, 0xe0, 0x21, 0x90, 0x38, 0x56, 0xe2, 0xc2, 0x11, 0xb5, 0x3c, 0x08, 0xf2, 0x7a, 0x9d,
	0xc4, 0x6d, 0x6a, 0x27, 0x15, 0xdc, 0x76, 0xd6, 0x33, 0xdf, 0xf7, 0xcd, 0xcc, 0xfa, 0x83, 0xcb,
	0xd8, 0x0e, 0xec, 0xfd, 0x16, 0xc6, 0x5d, 0x2b, 0x8a, 0x99, 0x60, 0xa4, 0x1a, 0xd1, 0x8e, 0x3c,
	0xb9, 0xac, 0x69, 0x45, 0xb4, 0xe3, 0xee, 0x51, 0x3f, 0xb4, 0xb0, 0x1d, 0xe8, 0x32, 0x15, 0xc3,
	0x56, 0xc0, 0xd3, 0x54, 0x7d, 0x69, 0x97, 0xb1, 0xdd, 0x26, 0xda, 0x34, 0xf2, 0x6d, 0x1a, 0x86,
	0x4c, 0x50, 0xe1, 0xb3, 0x50, 0x7d, 0x35, 0xb7, 0xc0, 0x7c, 0x95, 0xe0, 0xbe, 0xa4, 0x9d, 0xa7,
	0x9e, 0x17, 0x23, 0xe7, 0x1b, 0xdd, 0xad, 0xed, 0x17, 0xea, 0xec, 0xe0, 0x7e, 0x0b, 0xb9, 0x20,
	0x37, 0x60, 0x0e, 0xdb, 0x41, 0x9d, 0xa6, 0xb7, 0x55, 0x6d, 0x59, 0x5b, 0x99, 0x75, 0x00, 0xdb,
	0x81, 0xca, 0x33, 0x77, 0xe0, 0x66, 0x21, 0x0c, 0x8f, 0x58, 0xc8, 0x31, 0xc1, 0x89, 0x68, 0xe7,
	0x24, 0x4e, 0xd4, 0x2b, 0x22, 0x06, 0x00, 0xe5, 0x9c, 0xb9, 0x3e, 0x15, 0xe8, 0x55, 0x2b, 0xcb,
	0xda, 0xca, 0x8c, 0x33, 0x70, 0xd3, 0x93, 0xdb, 0xc7, 0xde, 0x18, 0xe0, 0x1c, 0x90, 0x5b, 0x48,
	0xd3, 0x93, 0x7b, 0x16, 0x4c, 0x5f, 0x6e, 0x61, 0xdb, 0xa5, 0x72, 0xd7, 0x61, 0x51, 0xf2, 0xbc,
	0x4e, 0x86, 0xee, 0x6e, 0xd2, 0x66, 0x33, 0x93, 0x48, 0x60, 0xd2, 0xa3, 0x82, 0x4a, 0xcc, 0x79,
	0x47, 0x9e, 0xc9, 0x02, 0x54, 0x04, 0x93, 0x28, 0xb3, 0x4e, 0x45, 0x30, 0xb3, 0x06, 0xd7, 0x4e,
	0x55, 0x2b, 0x65, 0x43, 0xca, 0xcd, 0x2e, 0x5c, 0x49, 0x77, 0xc0, 0xfc, 0x50, 0x60, 0x9c, 0x31,
	0x3d, 0x83, 0xf9, 0x28, 0xbd, 0xa9, 0x8b, 0x6e, 0x84, 0xb2, 0x64, 0x61, 0xed, 0xb6, 0x75, 0xd6,
	0x0b, 0xb2, 0x54, 0xfd, 0x9b, 0x6e, 0x84, 0xce, 0x5c, 0xd4, 0x0f, 0x48, 0x15, 0xa6, 0xd3, 0x10,
	0x95, 0xc8, 0x2c, 0x34, 0x1b, 0x70, 0x35, 0x4f, 0xad, 0x64, 0xf6, 0x2a, 0x62, 0x35, 0xbc, 0x2c,
	0x4c, 0xbe, 0xb4, 0x31, 0xe6, 0x3e, 0x0b, 0x25, 0xd6, 0x25, 0x27, 0x0b, 0xc9, 0x22, 0x4c, 0x61,
	0xc7, 0xe7, 0x82, 0x57, 0x2f, 0xc8, 0x79, 0xaa, 0xc8, 0xdc, 0x01, 0x7d, 0x90, 0x63, 0x3b, 0x4d,
	0xff, 0xe7, 0x5d, 0x9a, 0x6f, 0xe1, 0xfa, 0x50, 0x9e, 0x7e, 0x4b, 0x99, 0x70, 0x2d, 0x2f, 0x7c,
	0x09, 0xc0, 0x3d, 0xa8, 0xbb, 0xcc, 0xc3, 0xba, 0x9f, 0x3e, 0x86, 0x49, 0x67, 0xc6, 0x3d, 0xd8,
	0x64, 0x1e, 0x3e, 0xf7, 0x4e, 0x6c, 0x07, 0xff, 0xe3, 0x76, 0xe2, 0xfc, 0x76, 0xe2, 0x13, 0xdb,
	0xc1, 0xd3, 0xdb, 0xc1, 0xfc, 0x76, 0x70, 0xfc, 0xed, 0xac, 0x7d, 0x99, 0x81, 0x8b, 0x92, 0x84,
	0x7c, 0xd7, 0x60, 0x71, 0xb8, 0x0d, 0x90, 0xf5, 0xb3, 0xdb, 0x2a, 0x37, 0x21, 0xfd, 0xc9, 0x39,
	0xab, 0xd3, 0x6e, 0x4d, 0xeb, 0xc3, 0xcf, 0x3f, 0x9f, 0x2a, 0x2b, 0xe4, 0x8e, 0x1d, 0xd1, 0x4e,
	0x2d, 0xc3, 0xb1, 0x33, 0x1c, 0x3b, 0xf1, 0xcd, 0x01, 0xd7, 0x90, 0x7d, 0x0c, 0xf7, 0x87, 0xd2,
	0x3e, 0x0a, 0xdd, 0xa9, 0xb4, 0x8f, 0x62, 0x53, 0x1a, 0xa9, 0x8f, 0x01, 0xd7, 0x22, 0x5f, 0x35,
	0x80, 0xbe, 0x83, 0x90, 0x7b, 0x25, 0xec, 0xa7, 0xac, 0x4a, 0xbf, 0x3f, 0x46, 0xc5, 0x18, 0x1a,
	0xb9, 0x2c, 0xab, 0xbb, 0x89, 0xa8, 0xcf, 0x1a, 0x4c, 0xab, 0x87, 0x4d, 0x6a, 0x65, 0x6b, 0xce,
	0xd9, 0x9b, 0x6e, 0x8d, 0x9a, 0xae, 0xa4, 0xad, 0x4a, 0x69, 0xb7, 0x88, 0x59, 0xf4, 0x0c, 0x94,
	0x94, 0x6f, 0x1a, 0x2c, 0xe4, 0x6d, 0x80, 0x3c, 0x1c, 0x8d, 0x2e, 0xef, 0x4e, 0xfa, 0xa3, 0x31,
	0xab, 0x94, 0xd6, 0x35, 0xa9, 0xf5, 0x2e, 0x59, 0x2d, 0xd7, 0x5a, 0xcf, 0x7e, 0xd0, 0xfe, 0x28,
	0x71, 0xc4, 0x51, 0xe2, 0x78, 0xa3, 0xc4, 0x73, 0x8c, 0x12, 0x37, 0x9c, 0x1f, 0x47, 0x86, 0x76,
	0x78, 0x64, 0x68, 0xbf, 0x8f, 0x0c, 0xed, 0xe3, 0xb1, 0x31, 0x71, 0x78, 0x6c, 0x4c, 0xfc, 0x3a,
	0x36, 0x26, 0xde, 0x3d, 0xde, 0xf5, 0xc5, 0x5e, 0xab, 0x61, 0xb9, 0x2c, 0xb0, 0xb9, 0xef, 0xf9,
	0x2c, 0xa6, 0xb5, 0x26, 0x6d, 0xf0, 0x04, 0x07, 0x31, 0xae, 0x85, 0x28, 0x0e, 0x58, 0xfc, 0xde,
	0x0e, 0x98, 0xd7, 0x6a, 0x22, 0x97, 0xa8, 0x89, 0x55, 0xf2, 0xc6, 0x94, 0xa4, 0x7c, 0xf0, 0x37,
	0x00, 0x00, 0xff, 0xff, 0x18, 0xf3, 0xc9, 0xb9, 0x1e, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	PaxAddressByEVMAddress(ctx context.Context, in *QueryPaxAddressByEVMAddressRequest, opts ...grpc.CallOption) (*QueryPaxAddressByEVMAddressResponse, error)
	EVMAddressByPaxAddress(ctx context.Context, in *QueryEVMAddressByPaxAddressRequest, opts ...grpc.CallOption) (*QueryEVMAddressByPaxAddressResponse, error)
	StaticCall(ctx context.Context, in *QueryStaticCallRequest, opts ...grpc.CallOption) (*QueryStaticCallResponse, error)
	Pointer(ctx context.Context, in *QueryPointerRequest, opts ...grpc.CallOption) (*QueryPointerResponse, error)
	PointerVersion(ctx context.Context, in *QueryPointerVersionRequest, opts ...grpc.CallOption) (*QueryPointerVersionResponse, error)
	Pointee(ctx context.Context, in *QueryPointeeRequest, opts ...grpc.CallOption) (*QueryPointeeResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) PaxAddressByEVMAddress(ctx context.Context, in *QueryPaxAddressByEVMAddressRequest, opts ...grpc.CallOption) (*QueryPaxAddressByEVMAddressResponse, error) {
	out := new(QueryPaxAddressByEVMAddressResponse)
	err := c.cc.Invoke(ctx, "/paxprotocol.paxchain.evm.Query/PaxAddressByEVMAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EVMAddressByPaxAddress(ctx context.Context, in *QueryEVMAddressByPaxAddressRequest, opts ...grpc.CallOption) (*QueryEVMAddressByPaxAddressResponse, error) {
	out := new(QueryEVMAddressByPaxAddressResponse)
	err := c.cc.Invoke(ctx, "/paxprotocol.paxchain.evm.Query/EVMAddressByPaxAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) StaticCall(ctx context.Context, in *QueryStaticCallRequest, opts ...grpc.CallOption) (*QueryStaticCallResponse, error) {
	out := new(QueryStaticCallResponse)
	err := c.cc.Invoke(ctx, "/paxprotocol.paxchain.evm.Query/StaticCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Pointer(ctx context.Context, in *QueryPointerRequest, opts ...grpc.CallOption) (*QueryPointerResponse, error) {
	out := new(QueryPointerResponse)
	err := c.cc.Invoke(ctx, "/paxprotocol.paxchain.evm.Query/Pointer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PointerVersion(ctx context.Context, in *QueryPointerVersionRequest, opts ...grpc.CallOption) (*QueryPointerVersionResponse, error) {
	out := new(QueryPointerVersionResponse)
	err := c.cc.Invoke(ctx, "/paxprotocol.paxchain.evm.Query/PointerVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Pointee(ctx context.Context, in *QueryPointeeRequest, opts ...grpc.CallOption) (*QueryPointeeResponse, error) {
	out := new(QueryPointeeResponse)
	err := c.cc.Invoke(ctx, "/paxprotocol.paxchain.evm.Query/Pointee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	PaxAddressByEVMAddress(context.Context, *QueryPaxAddressByEVMAddressRequest) (*QueryPaxAddressByEVMAddressResponse, error)
	EVMAddressByPaxAddress(context.Context, *QueryEVMAddressByPaxAddressRequest) (*QueryEVMAddressByPaxAddressResponse, error)
	StaticCall(context.Context, *QueryStaticCallRequest) (*QueryStaticCallResponse, error)
	Pointer(context.Context, *QueryPointerRequest) (*QueryPointerResponse, error)
	PointerVersion(context.Context, *QueryPointerVersionRequest) (*QueryPointerVersionResponse, error)
	Pointee(context.Context, *QueryPointeeRequest) (*QueryPointeeResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) PaxAddressByEVMAddress(ctx context.Context, req *QueryPaxAddressByEVMAddressRequest) (*QueryPaxAddressByEVMAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PaxAddressByEVMAddress not implemented")
}
func (*UnimplementedQueryServer) EVMAddressByPaxAddress(ctx context.Context, req *QueryEVMAddressByPaxAddressRequest) (*QueryEVMAddressByPaxAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EVMAddressByPaxAddress not implemented")
}
func (*UnimplementedQueryServer) StaticCall(ctx context.Context, req *QueryStaticCallRequest) (*QueryStaticCallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaticCall not implemented")
}
func (*UnimplementedQueryServer) Pointer(ctx context.Context, req *QueryPointerRequest) (*QueryPointerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pointer not implemented")
}
func (*UnimplementedQueryServer) PointerVersion(ctx context.Context, req *QueryPointerVersionRequest) (*QueryPointerVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PointerVersion not implemented")
}
func (*UnimplementedQueryServer) Pointee(ctx context.Context, req *QueryPointeeRequest) (*QueryPointeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pointee not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_PaxAddressByEVMAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPaxAddressByEVMAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PaxAddressByEVMAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paxprotocol.paxchain.evm.Query/PaxAddressByEVMAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PaxAddressByEVMAddress(ctx, req.(*QueryPaxAddressByEVMAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EVMAddressByPaxAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEVMAddressByPaxAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EVMAddressByPaxAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paxprotocol.paxchain.evm.Query/EVMAddressByPaxAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EVMAddressByPaxAddress(ctx, req.(*QueryEVMAddressByPaxAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_StaticCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryStaticCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).StaticCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paxprotocol.paxchain.evm.Query/StaticCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).StaticCall(ctx, req.(*QueryStaticCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Pointer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPointerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Pointer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paxprotocol.paxchain.evm.Query/Pointer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Pointer(ctx, req.(*QueryPointerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PointerVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPointerVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PointerVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paxprotocol.paxchain.evm.Query/PointerVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PointerVersion(ctx, req.(*QueryPointerVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Pointee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPointeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Pointee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paxprotocol.paxchain.evm.Query/Pointee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Pointee(ctx, req.(*QueryPointeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "paxprotocol.paxchain.evm.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PaxAddressByEVMAddress",
			Handler:    _Query_PaxAddressByEVMAddress_Handler,
		},
		{
			MethodName: "EVMAddressByPaxAddress",
			Handler:    _Query_EVMAddressByPaxAddress_Handler,
		},
		{
			MethodName: "StaticCall",
			Handler:    _Query_StaticCall_Handler,
		},
		{
			MethodName: "Pointer",
			Handler:    _Query_Pointer_Handler,
		},
		{
			MethodName: "PointerVersion",
			Handler:    _Query_PointerVersion_Handler,
		},
		{
			MethodName: "Pointee",
			Handler:    _Query_Pointee_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "evm/query.proto",
}

func (m *QueryPaxAddressByEVMAddressRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPaxAddressByEVMAddressRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPaxAddressByEVMAddressRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EvmAddress) > 0 {
		i -= len(m.EvmAddress)
		copy(dAtA[i:], m.EvmAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.EvmAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryPaxAddressByEVMAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPaxAddressByEVMAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPaxAddressByEVMAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Associated {
		i--
		if m.Associated {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.PaxAddress) > 0 {
		i -= len(m.PaxAddress)
		copy(dAtA[i:], m.PaxAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.PaxAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryEVMAddressByPaxAddressRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEVMAddressByPaxAddressRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEVMAddressByPaxAddressRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PaxAddress) > 0 {
		i -= len(m.PaxAddress)
		copy(dAtA[i:], m.PaxAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.PaxAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryEVMAddressByPaxAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEVMAddressByPaxAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEVMAddressByPaxAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Associated {
		i--
		if m.Associated {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.EvmAddress) > 0 {
		i -= len(m.EvmAddress)
		copy(dAtA[i:], m.EvmAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.EvmAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryStaticCallRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryStaticCallRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryStaticCallRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.To) > 0 {
		i -= len(m.To)
		copy(dAtA[i:], m.To)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.To)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryStaticCallResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryStaticCallResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryStaticCallResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryPointerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPointerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPointerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Pointee) > 0 {
		i -= len(m.Pointee)
		copy(dAtA[i:], m.Pointee)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Pointee)))
		i--
		dAtA[i] = 0x12
	}
	if m.PointerType != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PointerType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryPointerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPointerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPointerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Exists {
		i--
		if m.Exists {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.Version != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Version))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Pointer) > 0 {
		i -= len(m.Pointer)
		copy(dAtA[i:], m.Pointer)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Pointer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryPointerVersionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPointerVersionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPointerVersionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PointerType != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PointerType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryPointerVersionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPointerVersionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPointerVersionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CwCodeId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.CwCodeId))
		i--
		dAtA[i] = 0x10
	}
	if m.Version != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Version))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryPointeeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPointeeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPointeeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Pointer) > 0 {
		i -= len(m.Pointer)
		copy(dAtA[i:], m.Pointer)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Pointer)))
		i--
		dAtA[i] = 0x12
	}
	if m.PointerType != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PointerType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryPointeeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPointeeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPointeeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Exists {
		i--
		if m.Exists {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.Version != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Version))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Pointee) > 0 {
		i -= len(m.Pointee)
		copy(dAtA[i:], m.Pointee)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Pointee)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryPaxAddressByEVMAddressRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EvmAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryPaxAddressByEVMAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PaxAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Associated {
		n += 2
	}
	return n
}

func (m *QueryEVMAddressByPaxAddressRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PaxAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryEVMAddressByPaxAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EvmAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Associated {
		n += 2
	}
	return n
}

func (m *QueryStaticCallRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.To)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryStaticCallResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryPointerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PointerType != 0 {
		n += 1 + sovQuery(uint64(m.PointerType))
	}
	l = len(m.Pointee)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryPointerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Pointer)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Version != 0 {
		n += 1 + sovQuery(uint64(m.Version))
	}
	if m.Exists {
		n += 2
	}
	return n
}

func (m *QueryPointerVersionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PointerType != 0 {
		n += 1 + sovQuery(uint64(m.PointerType))
	}
	return n
}

func (m *QueryPointerVersionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Version != 0 {
		n += 1 + sovQuery(uint64(m.Version))
	}
	if m.CwCodeId != 0 {
		n += 1 + sovQuery(uint64(m.CwCodeId))
	}
	return n
}

func (m *QueryPointeeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PointerType != 0 {
		n += 1 + sovQuery(uint64(m.PointerType))
	}
	l = len(m.Pointer)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryPointeeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Pointee)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Version != 0 {
		n += 1 + sovQuery(uint64(m.Version))
	}
	if m.Exists {
		n += 2
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryPaxAddressByEVMAddressRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPaxAddressByEVMAddressRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPaxAddressByEVMAddressRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvmAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvmAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPaxAddressByEVMAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPaxAddressByEVMAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPaxAddressByEVMAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaxAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PaxAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Associated", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Associated = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEVMAddressByPaxAddressRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEVMAddressByPaxAddressRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEVMAddressByPaxAddressRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaxAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PaxAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEVMAddressByPaxAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEVMAddressByPaxAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEVMAddressByPaxAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvmAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvmAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Associated", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Associated = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryStaticCallRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryStaticCallRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryStaticCallRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field To", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.To = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryStaticCallResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryStaticCallResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryStaticCallResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPointerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPointerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPointerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PointerType", wireType)
			}
			m.PointerType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PointerType |= PointerType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pointee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pointee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPointerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPointerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPointerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pointer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pointer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Exists", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Exists = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPointerVersionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPointerVersionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPointerVersionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PointerType", wireType)
			}
			m.PointerType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PointerType |= PointerType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPointerVersionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPointerVersionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPointerVersionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CwCodeId", wireType)
			}
			m.CwCodeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CwCodeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPointeeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPointeeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPointeeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PointerType", wireType)
			}
			m.PointerType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PointerType |= PointerType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pointer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pointer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPointeeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPointeeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPointeeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pointee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pointee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Exists", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Exists = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
