// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/applications/interchain_accounts/host/v1/host.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the set of on-chain interchain accounts parameters.
// The following parameters may be used to disable the host submodule.
type Params struct {
	// host_enabled enables or disables the host submodule.
	HostEnabled bool `protobuf:"varint,1,opt,name=host_enabled,json=hostEnabled,proto3" json:"host_enabled,omitempty" yaml:"host_enabled"`
	// allow_messages defines a list of sdk message typeURLs allowed to be executed on a host chain.
	AllowMessages []string `protobuf:"bytes,2,rep,name=allow_messages,json=allowMessages,proto3" json:"allow_messages,omitempty" yaml:"allow_messages"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_48e202774f13d08e, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetHostEnabled() bool {
	if m != nil {
		return m.HostEnabled
	}
	return false
}

func (m *Params) GetAllowMessages() []string {
	if m != nil {
		return m.AllowMessages
	}
	return nil
}

func init() {
	proto.RegisterType((*Params)(nil), "ibc.applications.interchain_accounts.host.v1.Params")
}

func init() {
	proto.RegisterFile("ibc/applications/interchain_accounts/host/v1/host.proto", fileDescriptor_48e202774f13d08e)
}

var fileDescriptor_48e202774f13d08e = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xbd, 0x4e, 0x32, 0x41,
	0x14, 0x86, 0xd9, 0xef, 0x4b, 0x88, 0xae, 0x3f, 0x05, 0x6a, 0x44, 0x8b, 0x81, 0x6c, 0x45, 0xe1,
	0xee, 0x04, 0x2d, 0x48, 0xa8, 0x0c, 0x89, 0xa5, 0x89, 0xa1, 0xb4, 0xc1, 0x33, 0xc3, 0x64, 0x99,
	0x38, 0x3b, 0x67, 0x33, 0x67, 0x00, 0xf1, 0x02, 0xac, 0xbd, 0x2c, 0x4b, 0x4a, 0x2b, 0x62, 0xe0,
	0x0e, 0xb8, 0x02, 0xb3, 0x8b, 0x89, 0x90, 0x58, 0xcd, 0xbc, 0xe7, 0x3d, 0xcf, 0x29, 0x9e, 0xb0,
	0xa3, 0x85, 0xe4, 0x90, 0xe7, 0x46, 0x4b, 0xf0, 0x1a, 0x2d, 0x71, 0x6d, 0xbd, 0x72, 0x72, 0x04,
	0xda, 0x0e, 0x40, 0x4a, 0x1c, 0x5b, 0x4f, 0x7c, 0x84, 0xe4, 0xf9, 0xa4, 0x5d, 0xbe, 0x49, 0xee,
	0xd0, 0x63, 0xed, 0x4a, 0x0b, 0x99, 0x6c, 0x83, 0xc9, 0x1f, 0x60, 0x52, 0x02, 0x93, 0xf6, 0xe5,
	0x69, 0x8a, 0x29, 0x96, 0x20, 0x2f, 0x7e, 0x9b, 0x1b, 0xd1, 0x5b, 0x10, 0x56, 0x1f, 0xc0, 0x41,
	0x46, 0xb5, 0x6e, 0x78, 0x58, 0xec, 0x0e, 0x94, 0x05, 0x61, 0xd4, 0xb0, 0x1e, 0x34, 0x83, 0xd6,
	0x5e, 0xef, 0x7c, 0xbd, 0x68, 0x9c, 0xcc, 0x20, 0x33, 0xdd, 0x68, 0xbb, 0x8d, 0xfa, 0x07, 0x45,
	0xbc, 0xdb, 0xa4, 0xda, 0x6d, 0x78, 0x0c, 0xc6, 0xe0, 0x74, 0x90, 0x29, 0x22, 0x48, 0x15, 0xd5,
	0xff, 0x35, 0xff, 0xb7, 0xf6, 0x7b, 0x17, 0xeb, 0x45, 0xe3, 0x6c, 0x43, 0xef, 0xf6, 0x51, 0xff,
	0xa8, 0x1c, 0xdc, 0xff, 0xe4, 0xde, 0xeb, 0xc7, 0x92, 0x05, 0xf3, 0x25, 0x0b, 0xbe, 0x96, 0x2c,
	0x78, 0x5f, 0xb1, 0xca, 0x7c, 0xc5, 0x2a, 0x9f, 0x2b, 0x56, 0x79, 0x7c, 0x4a, 0xb5, 0x1f, 0x8d,
	0x45, 0x22, 0x31, 0xe3, 0xa4, 0x87, 0x1a, 0x1d, 0xc4, 0x06, 0x04, 0xf1, 0x1c, 0x5e, 0x94, 0x72,
	0xb1, 0x55, 0x7e, 0x8a, 0xee, 0x79, 0xcb, 0x1a, 0xcf, 0x70, 0x38, 0x36, 0x8a, 0x0a, 0xab, 0xc4,
	0xaf, 0x3b, 0xf1, 0x6f, 0x15, 0xef, 0x0a, 0xf5, 0xb3, 0x5c, 0x91, 0xa8, 0x96, 0x2e, 0x6e, 0xbe,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x3c, 0xb9, 0x37, 0x8a, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AllowMessages) > 0 {
		for iNdEx := len(m.AllowMessages) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AllowMessages[iNdEx])
			copy(dAtA[i:], m.AllowMessages[iNdEx])
			i = encodeVarintHost(dAtA, i, uint64(len(m.AllowMessages[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if m.HostEnabled {
		i--
		if m.HostEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintHost(dAtA []byte, offset int, v uint64) int {
	offset -= sovHost(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.HostEnabled {
		n += 2
	}
	if len(m.AllowMessages) > 0 {
		for _, s := range m.AllowMessages {
			l = len(s)
			n += 1 + l + sovHost(uint64(l))
		}
	}
	return n
}

func sovHost(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozHost(x uint64) (n int) {
	return sovHost(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHost
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HostEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHost
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HostEnabled = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowMessages", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHost
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHost
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHost
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowMessages = append(m.AllowMessages, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHost(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHost
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipHost(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowHost
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHost
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHost
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthHost
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupHost
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthHost
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthHost        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowHost          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupHost = fmt.Errorf("proto: unexpected end of group")
)
