[package]
name = "layerx-porting-evm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "programs_porting_evm"

[dependencies]
layerx-programs-registry = { path = "../../crates/layerx-programs-registry" }
layerx-programs-runtime = { path = "../../crates/layerx-programs-runtime" }
layerx-program-sdk = { path = "../../sdk/rust" }

[lints]
workspace = true
