[package]
name = "layerx-platform-testnet"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "layerx-testnet-control"
path = "src/main.rs"

[dependencies]
native-tls.workspace = true
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
subtle.workspace = true
zeroize.workspace = true

[lints]
workspace = true
