#!/bin/sh
set -eu
: "${LAYERX_PENDING_PACKAGE_SEMVER:?LAYERX_PENDING_PACKAGE_SEMVER is required}"
: "${LAYERX_PENDING_WIRE_PROTOCOL_VERSION:?LAYERX_PENDING_WIRE_PROTOCOL_VERSION is required}"
: "${LAYERX_TESTNET_CORE_URL:?LAYERX_TESTNET_CORE_URL is required}"
: "${LAYERX_TESTNET_CORE_ADMIN_URL:?LAYERX_TESTNET_CORE_ADMIN_URL is required}"
: "${LAYERX_TESTNET_GATEWAY_URL:?LAYERX_TESTNET_GATEWAY_URL is required}"
: "${LAYERX_TESTNET_PAXEER_URL:?LAYERX_TESTNET_PAXEER_URL is required}"
: "${LAYERX_TESTNET_TLS_CERT_DER:?LAYERX_TESTNET_TLS_CERT_DER is required}"
: "${LAYERX_TESTNET_TLS_KEY_DER:?LAYERX_TESTNET_TLS_KEY_DER is required}"
: "${LAYERX_OUTBOUND_CA_DER:?LAYERX_OUTBOUND_CA_DER is required}"
: "${LAYERX_TESTNET_BACKEND_ADMIN_TOKEN_FILE:?LAYERX_TESTNET_BACKEND_ADMIN_TOKEN_FILE is required}"
: "${LAYERX_TESTNET_CONTROL_ADMIN_TOKEN_FILE:?LAYERX_TESTNET_CONTROL_ADMIN_TOKEN_FILE is required}"
test -r "$LAYERX_TESTNET_TLS_CERT_DER"
test -r "$LAYERX_TESTNET_TLS_KEY_DER"
test -r "$LAYERX_OUTBOUND_CA_DER"
test -r "$LAYERX_TESTNET_BACKEND_ADMIN_TOKEN_FILE"
test -r "$LAYERX_TESTNET_CONTROL_ADMIN_TOKEN_FILE"
exec layerx-testnet-control
