export const COPY_CATALOG_VERSION = "1.3.0" as const;

export const BANNED_VOCABULARY = [
  "DID",
  "session key",
  "capability",
  "nullifier",
  "checkpoint",
  "payload",
  "canonical",
  "idempotency",
  "attestation",
  "proof",
] as const;

export const DATE_FORMAT = "dd MMM yyyy, HH:mm z" as const;
export const AMOUNT_FORMAT = "{sign}{amount} {currencyCode}" as const;

export type CopySurface = "default" | "technical" | "explorer";
export type CopyKind = "action" | "body" | "format" | "status";

export interface CopyEntry {
  readonly key: string;
  readonly message: string;
  readonly context: string;
  readonly surface: CopySurface;
  readonly kind: CopyKind;
  readonly moneyAdjacent: boolean;
}

export const copyEntries = [
  { key: "application.name", message: "LayerX Human Interface", context: "Accessible product name and application metadata.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "navigation.home", message: "Home", context: "Authenticated application home navigation and heading.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "navigation.agents", message: "Agents", context: "Managed agents navigation.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "navigation.activity", message: "Activity", context: "Account activity navigation.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "navigation.more", message: "More", context: "Additional application destinations navigation.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "app.home.summary", message: "Your account tools and recent activity are available here.", context: "Authenticated plane home introduction.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "explorer.title", message: "LayerX Explorer", context: "Public explorer page heading.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.summary", message: "Look up public LayerX activity and verify its records.", context: "Public explorer introduction.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "action.open_app", message: "Open app", context: "Move from the public explorer into the authenticated application.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "action.open_explorer", message: "Open explorer", context: "Move from the landing surface into the public explorer.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "status.getting_ready", message: "Getting ready", context: "Prepared activity that has not been signed.", surface: "default", kind: "status", moneyAdjacent: true },
  { key: "status.sending", message: "Sending", context: "Submitted activity without a receipt yet.", surface: "default", kind: "status", moneyAdjacent: true },
  { key: "status.processing", message: "Processing", context: "Executed activity awaiting final settlement.", surface: "default", kind: "status", moneyAdjacent: true },
  { key: "status.done", message: "Done", context: "Shown only when a LayerX receipt verifies.", surface: "default", kind: "status", moneyAdjacent: true },
  { key: "status.done_finalised", message: "Done, finalised", context: "Receipt whose settlement finality verifies.", surface: "default", kind: "status", moneyAdjacent: true },
  { key: "status.still_checking", message: "Still checking — don't send again", context: "Unknown submission outcome; duplicate controls stay locked.", surface: "default", kind: "status", moneyAdjacent: true },
  { key: "status.refused", message: "Didn't go through", context: "Typed refusal or failure, paired with whether money moved.", surface: "default", kind: "status", moneyAdjacent: true },
  { key: "status.waiting_for_you", message: "Waiting for you", context: "Activity held for a human decision.", surface: "default", kind: "status", moneyAdjacent: true },
  { key: "status.waiting_for_wallet", message: "Waiting for wallet", context: "Deposit is waiting for the explicit wallet signature.", surface: "default", kind: "status", moneyAdjacent: true },
  { key: "status.confirming_on_paxeer", message: "Confirming on Paxeer", context: "Custody transaction is progressing toward Paxeer finality.", surface: "default", kind: "status", moneyAdjacent: true },
  { key: "status.crediting", message: "Crediting", context: "Final custody evidence is being credited on LayerX.", surface: "default", kind: "status", moneyAdjacent: true },
  { key: "status.waiting_for_settlement", message: "Waiting for settlement", context: "Withdrawal debit is waiting for its settlement window.", surface: "default", kind: "status", moneyAdjacent: true },
  { key: "status.ready_to_claim", message: "Ready to claim", context: "Withdrawal can now be claimed in the bound wallet.", surface: "default", kind: "status", moneyAdjacent: true },
  { key: "status.paid_out", message: "Paid out", context: "Paxeer payout transaction reached verified finality.", surface: "default", kind: "status", moneyAdjacent: true },
  { key: "approval.count", message: "{count, plural, =0 {No approvals waiting} one {# approval waiting} other {# approvals waiting}}", context: "Approval badge and inbox count with ICU plural handling.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "approval.activity.move_money", message: "Move {amount} {asset} to {counterparty}. Fees can be up to {fee}.", context: "Digest-bound asset movement approval content.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "approval.activity.add_money", message: "Add {amount} {asset} to {counterparty}. Fees can be up to {fee}.", context: "Digest-bound Paxeer credit approval content.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "approval.activity.withdrawal_wallet", message: "Use {counterparty} for withdrawals. Fees can be up to {fee}.", context: "Digest-bound payout wallet approval content.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "approval.activity.unrenderable", message: "This request cannot be reviewed here.", context: "Safe non-approvable copy for an unknown activity class.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "movement.direction", message: "{direction, select, inbound {Money in} outbound {Money out} other {Money moved}}", context: "Accessible direction wording selected independently of color.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "state.loading", message: "Getting ready", context: "Screen data is loading from the real service.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "state.loading.body", message: "Your information is being checked.", context: "Layout-reserving loading state explanation.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "state.empty", message: "Nothing here yet", context: "Screen has loaded successfully without records.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "state.empty.body", message: "New items will appear here when they are available.", context: "Loaded empty state explanation.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "state.error", message: "Something went wrong", context: "Screen could not load and offers recovery actions.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "state.error.body", message: "This screen could not be shown.", context: "Error state explanation without exposing internal details.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "state.offline", message: "You're offline", context: "Screen cannot reach the service and offers retry.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "state.offline.body", message: "Reconnect to refresh this screen.", context: "Per-screen offline recovery guidance.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "state.offline.banner", message: "You're offline. Information may be out of date.", context: "Persistent application-wide offline banner.", surface: "default", kind: "status", moneyAdjacent: false },
  { key: "state.degraded", message: "Some information may be delayed", context: "Screen is usable with explicitly stale information.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "state.degraded.age", message: "Last updated {age}.", context: "Age of stale information on a degraded screen.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "state.degraded.reference", message: "Current view is based on {referencePoint}.", context: "Reference point for stale information on a degraded screen.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "state.still_checking.body", message: "Your money is safe while the result is checked. Do not send again.", context: "Unknown money outcome guidance while automatic lookup continues.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "state.still_checking.locked", message: "Sending again is locked until the result is known.", context: "Disabled reason for duplicate money controls.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "error.money.not_started", message: "This screen error did not start a new money movement.", context: "Money consequence for a route rendering failure.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "error.technical.title", message: "Technical details", context: "Collapsed diagnostic disclosure title.", surface: "technical", kind: "body", moneyAdjacent: false },
  { key: "error.technical.machine_code", message: "Code: {machineCode}", context: "Non-sensitive machine-readable error code.", surface: "technical", kind: "body", moneyAdjacent: false },
  { key: "error.technical.trace", message: "Trace: {traceId}", context: "Non-sensitive trace identifier for support.", surface: "technical", kind: "body", moneyAdjacent: false },
  { key: "report.consent.title", message: "Send an error report?", context: "Consent confirmation title before submitting diagnostic context.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "report.consent.body", message: "This sends the trace, error code, and screen name. It does not include names, balances, or entered values.", context: "Explicit scope of consented redacted diagnostic submission.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "report.submit", message: "Send report", context: "Consent action for a redacted diagnostic report.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "report.saved", message: "Report saved", context: "Confirmation after the server durably accepts a diagnostic report.", surface: "default", kind: "status", moneyAdjacent: false },
  { key: "report.saved.body", message: "Support can use the trace shown in technical details.", context: "Server-confirmed diagnostic report detail.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "report.pending", message: "Report waiting for connection", context: "Explicit pending status for an offline diagnostic report.", surface: "default", kind: "status", moneyAdjacent: false },
  { key: "report.pending.body", message: "It will be sent when you're back online.", context: "Offline report queue and reconnect behavior.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "report.failed", message: "The report could not be saved. You can try again.", context: "Honest diagnostic report submission failure.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "queue.waiting", message: "This update will continue when you're online.", context: "Honest queued non-money action status.", surface: "default", kind: "status", moneyAdjacent: false },
  { key: "queue.money.not_queued", message: "Money movements are never queued. Return when you're online.", context: "Offline money safety explanation.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "action.retry", message: "Retry", context: "Retry the current read without duplicating a money movement.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "action.reload", message: "Reload", context: "Reload a structurally broken screen.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "action.report", message: "Report", context: "Submit consented non-sensitive diagnostic context.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "action.send_again", message: "Send again", context: "Duplicate money action shown disabled while an outcome is unknown.", surface: "default", kind: "action", moneyAdjacent: true },
  { key: "action.dismiss", message: "Dismiss", context: "Dismiss a completed status message.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "action.cancel", message: "Cancel", context: "Dismiss a confirmation without applying its action.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "action.copy", message: "Copy", context: "Copy an explicitly copyable identifier.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "action.copied", message: "Copied", context: "Confirm that an identifier was copied.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "action.copy_failed", message: "Couldn’t copy", context: "Announce that an identifier could not be copied.", surface: "default", kind: "status", moneyAdjacent: false },
  { key: "confirmation.incomplete", message: "Confirmation is incomplete.", context: "Explain why an irreversible confirmation remains disabled.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "confirmation.type_exact", message: "Type {expectedValue} exactly to continue.", context: "Disabled reason for an irreversible typed confirmation.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "confirmation.type_to_confirm", message: "Type {expectedValue} to confirm", context: "Label for an irreversible typed-confirmation field.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "fee.disclosure.title", message: "How this fee is calculated", context: "Heading for the numbered fee calculation disclosure.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "fee.disclosure.total", message: "Total fee", context: "Label for the computed total in a fee calculation disclosure.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "settings.title", message: "Settings", context: "Settings hub heading.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "settings.summary", message: "Manage your profile, security, wallet, notifications and privacy.", context: "Settings hub introduction.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "settings.section.profile", message: "Profile", context: "Profile settings section.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "settings.section.security", message: "Security", context: "Security settings section.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "settings.section.wallet", message: "Linked wallet", context: "Wallet settings section.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "settings.section.notifications", message: "Notifications", context: "Notification settings section.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "settings.section.advanced", message: "Advanced", context: "Advanced settings section.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "settings.section.help", message: "Help", context: "Help settings section.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "settings.profile.display_name", message: "Display name", context: "Editable declared-local profile name.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "settings.profile.avatar", message: "Avatar address", context: "Editable declared-local profile avatar URL.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "settings.profile.name_required", message: "Enter a display name before saving.", context: "Disabled reason for an empty profile name.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "settings.action.edit", message: "Edit", context: "Open profile editing controls.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "settings.action.save", message: "Save changes", context: "Persist a settings change.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "settings.save.saved", message: "Changes saved", context: "Settings mutation confirmation.", surface: "default", kind: "status", moneyAdjacent: false },
  { key: "settings.save.failed", message: "Changes could not be saved. Try again.", context: "Settings mutation failure.", surface: "default", kind: "status", moneyAdjacent: false },
  { key: "settings.security.title", message: "Passkeys and devices", context: "Security-center settings row.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "settings.security.current", message: "Review sign-in methods and active sessions", context: "Security-center current-value summary.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "settings.wallet.title", message: "Payout wallet", context: "Linked payout wallet settings row.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "settings.wallet.none", message: "Not linked", context: "No payout wallet is linked.", surface: "default", kind: "status", moneyAdjacent: false },
  { key: "settings.wallet.binding", message: "Linking", context: "A payout wallet binding is underway.", surface: "default", kind: "status", moneyAdjacent: false },
  { key: "settings.wallet.bound", message: "Linked", context: "A payout wallet is linked when no address is present.", surface: "default", kind: "status", moneyAdjacent: false },
  { key: "settings.wallet.rebinding", message: "Changing wallet", context: "A payout wallet rebinding is underway.", surface: "default", kind: "status", moneyAdjacent: false },
  { key: "settings.notifications.detail.title", message: "Notification detail", context: "Financial detail-level preference label.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "settings.notifications.detail.body", message: "Choose how much financial detail notifications may include.", context: "Financial detail-level preference explanation.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "settings.notifications.detail.minimal", message: "Minimal", context: "Minimal notification detail option.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "settings.notifications.detail.summary", message: "Summary", context: "Summary notification detail option.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "settings.notifications.detail.full", message: "Full", context: "Full notification detail option.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "settings.notifications.channel.push", message: "Push", context: "Push notification channel.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "settings.notifications.channel.email", message: "Email", context: "Email notification channel.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "settings.notifications.channel.in_app", message: "In app", context: "In-application notification channel.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "settings.notifications.channel.enabled", message: "Use this channel", context: "Channel-level notification toggle label.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "settings.notifications.channel.enabled.body", message: "Event choices below apply while this channel is on.", context: "Channel-level notification toggle explanation.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "settings.notifications.channel.toggle", message: "Use {channel} notifications", context: "Accessible channel toggle label.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "settings.notifications.class.toggle", message: "Send {notification} through {channel}", context: "Accessible event-class toggle label.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "settings.notifications.class.approval_waiting", message: "Approval waiting", context: "Approval notification class.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "settings.notifications.class.money_arrived", message: "Money arrived", context: "Money-arrival notification class.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "settings.notifications.class.journey_finished", message: "Activity finished", context: "Journey-completion notification class.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "settings.notifications.class.claim_ready", message: "Claim ready", context: "Withdrawal-claim notification class.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "settings.notifications.class.security_new_device", message: "New device", context: "New-device security notification class.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "settings.notifications.class.security_recovery", message: "Recovery started", context: "Recovery security notification class.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "settings.notifications.class.security_wallet_rebinding", message: "Wallet changed", context: "Wallet-rebinding security notification class.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "settings.notifications.class.security_key_rotation", message: "Security key changed", context: "Key-rotation security notification class.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "settings.notifications.class.service_status", message: "Service status", context: "Service degradation notification class.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "settings.notifications.non_suppressible", message: "Recovery and wallet-change alerts must remain on in at least one channel.", context: "Refusal when a security-critical class would be fully suppressed.", surface: "default", kind: "status", moneyAdjacent: false },
  { key: "settings.notifications.non_suppressible.caption", message: "Always on in at least one channel", context: "Security-critical notification class explanation.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "settings.privacy.title", message: "Privacy mode", context: "Privacy masking setting.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "settings.privacy.body", message: "Hide balances, subtotals, spend figures and notification amounts everywhere.", context: "Privacy masking behavior explanation.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "settings.privacy.toggle", message: "Mask private figures", context: "Accessible privacy-mode toggle label.", surface: "default", kind: "action", moneyAdjacent: true },
  { key: "settings.privacy.on", message: "On", context: "Privacy mode current value.", surface: "default", kind: "status", moneyAdjacent: false },
  { key: "settings.privacy.off", message: "Off", context: "Privacy mode current value.", surface: "default", kind: "status", moneyAdjacent: false },
  { key: "privacy.hidden", message: "Hidden while privacy mode is on", context: "Accessible replacement for a masked private figure.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "settings.help.support", message: "Support", context: "Support destination row.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "settings.help.support.body", message: "Get help or review an existing support conversation", context: "Support destination summary.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "explorer.navigation.label", message: "Explorer sections", context: "Public explorer navigation label.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.navigation.overview", message: "Overview", context: "Public explorer overview navigation.", surface: "explorer", kind: "action", moneyAdjacent: false },
  { key: "explorer.navigation.checkpoints", message: "Checkpoints", context: "Public explorer checkpoints navigation.", surface: "explorer", kind: "action", moneyAdjacent: false },
  { key: "explorer.navigation.batches", message: "Batches", context: "Public explorer batches navigation.", surface: "explorer", kind: "action", moneyAdjacent: false },
  { key: "explorer.navigation.verify", message: "Verify evidence", context: "Public explorer verifier navigation.", surface: "explorer", kind: "action", moneyAdjacent: false },
  { key: "explorer.freshness.current", message: "Index is current", context: "Explorer index freshness status at the observed head.", surface: "explorer", kind: "status", moneyAdjacent: false },
  { key: "explorer.freshness.behind", message: "Index is catching up", context: "Explorer index is behind the observed head.", surface: "explorer", kind: "status", moneyAdjacent: false },
  { key: "explorer.freshness.unavailable", message: "Index freshness is unavailable", context: "Explorer cannot currently retrieve its index position.", surface: "explorer", kind: "status", moneyAdjacent: false },
  { key: "explorer.freshness.unavailable.body", message: "Public records cannot be shown until the explorer service responds.", context: "Honest explorer service unavailable explanation.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.freshness.detail", message: "Indexed batch {indexedBatch} of observed batch {observedBatch}; {batchesBehind} behind. Latest indexed checkpoint: {checkpoint}.", context: "Exact explorer index position on every public page.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.lookup.receipt.title", message: "Find a receipt", context: "Receipt lookup panel heading.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.lookup.receipt.label", message: "Receipt or activity identifier", context: "Receipt lookup input label.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.lookup.receipt.placeholder", message: "64-character hexadecimal identifier", context: "Receipt lookup placeholder.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.lookup.account.title", message: "View an account", context: "Public account lookup panel heading.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.lookup.account.label", message: "Account identifier", context: "Public account lookup input label.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.lookup.account.placeholder", message: "64-character hexadecimal account", context: "Public account lookup placeholder.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.lookup.action", message: "Look up", context: "Submit a public explorer lookup.", surface: "explorer", kind: "action", moneyAdjacent: false },
  { key: "explorer.checkpoints.title", message: "Checkpoints", context: "Checkpoint browse page heading.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.checkpoints.body", message: "Browse finalised checkpoints from newest to oldest.", context: "Checkpoint browse page explanation.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.checkpoints.recent", message: "Recent checkpoints", context: "Recent checkpoint table heading.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.checkpoints.table", message: "Public checkpoints", context: "Accessible checkpoint table caption.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.checkpoint.title", message: "Checkpoint", context: "Checkpoint detail page heading.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.checkpoint.facts", message: "Checkpoint facts and their verification", context: "Accessible checkpoint detail table caption.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.batches.title", message: "Batches", context: "Batch browse page heading.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.batches.body", message: "Browse complete public data-availability batches from newest to oldest.", context: "Batch browse page explanation.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.batches.recent", message: "Recent batches", context: "Recent batch table heading.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.batches.table", message: "Public batches", context: "Accessible batch table caption.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.batch.title", message: "Batch", context: "Batch detail page heading.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.batch.facts", message: "Batch facts and their verification", context: "Accessible batch detail table caption.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.receipt.title", message: "Receipt", context: "Receipt detail page heading.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.receipt.facts", message: "Receipt facts and their verification", context: "Accessible receipt detail table caption.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.receipt.bytes", message: "Canonical receipt bytes", context: "Exact public receipt material heading.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.account.title", message: "Account activity", context: "Public account activity page heading.", surface: "explorer", kind: "body", moneyAdjacent: true },
  { key: "explorer.account.table", message: "Receipt-verified public account activity", context: "Accessible public account table caption.", surface: "explorer", kind: "body", moneyAdjacent: true },
  { key: "explorer.not_found", message: "No matching public record", context: "Public explorer record missing status.", surface: "explorer", kind: "status", moneyAdjacent: false },
  { key: "explorer.not_found.body", message: "Check the full identifier and try the lookup again.", context: "Public explorer record missing explanation.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.pagination.older", message: "Older records", context: "Continue public explorer pagination.", surface: "explorer", kind: "action", moneyAdjacent: false },
  { key: "explorer.column.fact", message: "Fact", context: "Explorer fact table column.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.column.value", message: "Value", context: "Explorer value table column.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.column.batch", message: "Batch", context: "Explorer batch column.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.column.checkpoint", message: "Checkpoint", context: "Explorer checkpoint column.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.column.receipt", message: "Receipt", context: "Explorer receipt column.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.column.sequence", message: "Sequence", context: "Explorer sequence column.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.column.sequences", message: "Sequences", context: "Explorer sequence range column.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.column.signatures", message: "Signatures", context: "Explorer checkpoint signature threshold column.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.column.activities", message: "Activities", context: "Explorer activity-count column.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.column.receipts", message: "Receipts", context: "Explorer receipt-count column.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.column.events", message: "Events", context: "Explorer event-count column.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.column.bytes", message: "Bytes", context: "Explorer public byte-count column.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.column.operation", message: "Operation", context: "Explorer operation-code column.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.column.amount", message: "Amount in protocol units", context: "Explorer receipt-backed raw amount column.", surface: "explorer", kind: "body", moneyAdjacent: true },
  { key: "explorer.column.result", message: "Result code", context: "Explorer protocol result-code column.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.column.verification", message: "Verification", context: "Explorer achieved-verification column.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.fact.first_sequence", message: "First sequence", context: "Checkpoint first sequence fact.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.fact.last_sequence", message: "Last sequence", context: "Checkpoint last sequence fact.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.fact.ordinal", message: "Ordinal in batch", context: "Receipt ordinal fact.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.value.none", message: "None", context: "Explorer absent optional value.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.verification.unverified", message: "Unverified", context: "No explorer verification evidence passed.", surface: "explorer", kind: "status", moneyAdjacent: false },
  { key: "explorer.verification.sequencer_signed", message: "Sequencer signed", context: "Explorer sequencer signature verification level.", surface: "explorer", kind: "status", moneyAdjacent: false },
  { key: "explorer.verification.batch_included", message: "Batch included", context: "Explorer batch-inclusion verification level.", surface: "explorer", kind: "status", moneyAdjacent: false },
  { key: "explorer.verification.state_proven", message: "State proven", context: "Explorer state-inclusion verification level.", surface: "explorer", kind: "status", moneyAdjacent: false },
  { key: "explorer.verification.checkpoint_finalised", message: "Checkpoint finalised", context: "Explorer checkpoint-finality verification level.", surface: "explorer", kind: "status", moneyAdjacent: false },
  { key: "explorer.verification.settlement_anchored", message: "Settlement anchored", context: "Explorer settlement-anchor verification level.", surface: "explorer", kind: "status", moneyAdjacent: false },
  { key: "explorer.verify.title", message: "Verify evidence", context: "Public evidence verifier page heading.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.verify.body", message: "Check pasted protocol evidence independently from the explorer index.", context: "Public evidence verifier explanation.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.verify.form.title", message: "Evidence input", context: "Public evidence verifier form heading.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.verify.kind.label", message: "Evidence type", context: "Public verifier evidence-kind selector label.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.verify.kind.receipt", message: "Receipt", context: "Public verifier receipt option.", surface: "explorer", kind: "action", moneyAdjacent: false },
  { key: "explorer.verify.kind.activity", message: "Activity inclusion", context: "Public verifier activity-inclusion option.", surface: "explorer", kind: "action", moneyAdjacent: false },
  { key: "explorer.verify.kind.state", message: "State inclusion", context: "Public verifier state-inclusion option.", surface: "explorer", kind: "action", moneyAdjacent: false },
  { key: "explorer.verify.evidence.label", message: "Canonical bytes or inclusion bundle", context: "Public verifier pasted evidence label.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.verify.evidence.placeholder", message: "Paste base64url receipt bytes or the encoded inclusion bundle", context: "Public verifier input placeholder.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.verify.evidence.required", message: "Paste evidence before verifying.", context: "Disabled reason for an empty verifier input.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.verify.action", message: "Verify", context: "Submit public evidence for independent verification.", surface: "explorer", kind: "action", moneyAdjacent: false },
  { key: "explorer.verify.refused", message: "This evidence did not verify.", context: "Public verifier fail-closed result.", surface: "explorer", kind: "status", moneyAdjacent: false },
  { key: "explorer.verify.unavailable", message: "Verification is temporarily unavailable.", context: "Public verifier service unavailable result.", surface: "explorer", kind: "status", moneyAdjacent: false },
  { key: "explorer.verify.result.table", message: "Independent verification result", context: "Accessible public verifier result table caption.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.verify.result.kind", message: "Evidence type", context: "Public verifier result kind fact.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.verify.result.header", message: "Header digest", context: "Public verifier header digest fact.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "explorer.verify.result.root", message: "Verified root", context: "Public verifier proof root fact.", surface: "explorer", kind: "body", moneyAdjacent: false },
  { key: "onboarding.stage.creating-your-account", message: "Creating your account", context: "Onboarding journey stage reported by the service.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "onboarding.stage.adding-your-passkey", message: "Adding your passkey", context: "Onboarding journey stage reported by the service.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "onboarding.stage.setting-up-your-protocol-identity", message: "Activating your account", context: "Plain-language presentation of the onboarding identity stage reported by the service.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "onboarding.stage.putting-recovery-in-place", message: "Putting recovery in place", context: "Onboarding journey stage reported by the service.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "onboarding.create.title", message: "Create your account", context: "First onboarding decision screen heading.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "onboarding.create.body", message: "An email and a passkey are all you need.", context: "First onboarding decision screen introduction.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "onboarding.email.label", message: "Email", context: "Account email field label.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "onboarding.name.label", message: "Name", context: "Account display name field label.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "onboarding.create.action", message: "Continue", context: "Submit the account details screen.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "onboarding.passkey.title", message: "Add your passkey", context: "Passkey onboarding decision screen heading.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "onboarding.passkey.body", message: "Your passkey signs you in with your face, fingerprint or screen lock. There is nothing to remember.", context: "Plain-language passkey explanation.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "onboarding.passkey.action", message: "Create your passkey", context: "Start the passkey ceremony.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "onboarding.passkey.resume.body", message: "Your account details and passkey are saved. Confirm your passkey once more to continue setup.", context: "Resume copy after registration completed but opening the account did not.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "onboarding.passkey.resume.action", message: "Continue setup", context: "Resume onboarding without registering another passkey.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "onboarding.progress.title", message: "Setting up your account", context: "Onboarding activation progress heading.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "onboarding.progress.body", message: "The first steps are done. The remaining setup runs on our side and usually takes a few minutes.", context: "What is happening and roughly how long activation takes.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "onboarding.progress.safe_to_close", message: "It's safe to close this app. Setup continues on its own and picks up where it left off.", context: "Explicit safe-to-close guidance during activation.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "onboarding.pending.body", message: "The setup service can't be reached right now, so the remaining steps are waiting in line. They continue automatically and nothing you did is lost.", context: "Honest queued presentation while the protocol layer is unavailable.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "onboarding.active", message: "Your account is active", context: "Shown only when the protocol identity stage carries verified receipt evidence.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "onboarding.not_active", message: "Your account isn't active yet", context: "Honest not-ready statement while activation is unverified.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "onboarding.failure.title", message: "That step didn't finish", context: "Per-stage onboarding failure heading.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "onboarding.failure.stage", message: "The service could not finish this step. Completed steps are still saved.", context: "Plain-language explanation for a refused onboarding stage.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "onboarding.failure.preserved", message: "Your progress is saved. Finished steps stay finished.", context: "Journey preservation statement after a stage failure.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "onboarding.resume.action", message: "Pick up where you left off", context: "Resume the onboarding journey without restarting completed stages.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "onboarding.signin.title", message: "Sign in", context: "Sign-in decision screen heading.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "onboarding.signin.body", message: "Use the passkey you created when you signed up.", context: "Sign-in decision screen introduction.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "onboarding.signin.action", message: "Sign in with your passkey", context: "Start the sign-in passkey ceremony.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "onboarding.signin.switch", message: "Sign in instead", context: "Switch from account creation to sign-in.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "onboarding.create.switch", message: "Create an account", context: "Switch from sign-in to account creation.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "onboarding.signin.done", message: "You're signed in", context: "Sign-in completion heading.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "onboarding.signin.continue", message: "Go to your account", context: "Leave the sign-in surface for the authenticated plane.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "onboarding.ceremony.cancelled", message: "The passkey step was cancelled or couldn't finish on this device. You can try again.", context: "Browser passkey ceremony failure explanation.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "device.list.title", message: "Devices", context: "Device inventory screen heading.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "device.list.body", message: "Every device that can open your account, with its latest activity.", context: "Device inventory screen introduction.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "device.current", message: "This device", context: "Marks the session inventory row for the current device.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "device.opened", message: "First signed in {when}", context: "When a device first opened a session.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "device.last_active", message: "Last active {when}", context: "Latest activity for a device session.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "notification.new-device.title", message: "New device signed in", context: "Security notification title emitted when a new device opens a session.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "notification.new-device.body", message: "Your account was opened on a device it hasn't used before. If this was you, there's nothing to do.", context: "Security notification body for a new device session.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "notification.security-new-device.title", message: "New device signed in", context: "Security event notification title for a newly recorded device.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "notification.security-new-device.body", message: "A new device signed in to your account.", context: "Security event notification body for a newly recorded device.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "notification.action.review-devices", message: "Review devices", context: "Security notification action that opens the device list.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "error.account.email_invalid", message: "Enter a real email address.", context: "Typed account creation refusal for an invalid email.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "error.account.name_required", message: "Enter your name.", context: "Typed account creation refusal for a missing name.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "error.account.exists", message: "That email already has an account. Sign in instead.", context: "Typed account creation refusal for an existing email.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "error.passkey.ceremony_failed", message: "That security step didn't complete. You can try again.", context: "Typed passkey ceremony verification refusal.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "error.passkey.expired", message: "That security step timed out. Start it again.", context: "Typed refusal for an expired passkey ceremony.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "error.signin.unknown_email", message: "No account was found for that email.", context: "Typed sign-in refusal for an unknown email.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "error.signin.no_passkey", message: "That sign-in didn't match a passkey on this account.", context: "Typed sign-in refusal for an unrecognised credential.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "error.session.signed_out", message: "You're signed out. Sign in to continue.", context: "Typed refusal for a missing or ended session.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "error.service.unavailable", message: "This can't be done right now. Try again shortly.", context: "Typed refusal when the service host is not available.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "home.balance.label", message: "Verified balance", context: "Home balance heading with explicit verification wording.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "home.balance.freshness", message: "Checked {when}", context: "Freshness age shown beside the verified balance.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "home.balance.unavailable", message: "Your balance can't be shown right now", context: "Honest balance fallback when no verified figure is available.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "home.balance.hidden", message: "Balance hidden", context: "Announced and shown while the privacy toggle hides amounts.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "home.balance.hide", message: "Hide amounts", context: "Privacy action that masks every amount on the screen.", surface: "default", kind: "action", moneyAdjacent: true },
  { key: "home.balance.show", message: "Show amounts", context: "Privacy action that reveals every amount on the screen.", surface: "default", kind: "action", moneyAdjacent: true },
  { key: "home.actions.add", message: "Add money", context: "Primary home action that starts a deposit.", surface: "default", kind: "action", moneyAdjacent: true },
  { key: "home.actions.move", message: "Move money", context: "Primary home action that starts the move wizard.", surface: "default", kind: "action", moneyAdjacent: true },
  { key: "home.actions.withdraw", message: "Withdraw", context: "Primary home action that starts a withdrawal.", surface: "default", kind: "action", moneyAdjacent: true },
  { key: "home.agents.title", message: "Your agents", context: "Home section heading for managed agents.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "home.agents.count", message: "{count, plural, =0 {No agents yet} one {# agent} other {# agents}}", context: "Managed agent count in the home summary.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "home.agents.spent", message: "Spent {spent} of {limit} this month", context: "Per-agent spend against its monthly limit on home.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "home.activity.title", message: "Recent activity", context: "Home section heading for recent account activity.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "home.activity.empty", message: "No activity yet", context: "Home recent-activity section with no records.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "home.approvals.review", message: "Review approvals", context: "Navigate from the home approval badge to the inbox.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "verification.unverified", message: "Not verified yet", context: "Money figure without verified backing evidence.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "verification.receipt_verified", message: "Receipt-verified", context: "Money figure backed by a verified LayerX receipt.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "verification.checkpoint_finalised", message: "Finalised", context: "Money figure backed by finalised settlement evidence.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "verification.paxeer_finalised", message: "Finalised on Paxeer", context: "Money figure backed by Paxeer finality evidence.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.title", message: "Move money", context: "Move wizard page heading.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.step.who.label", message: "Who", context: "Move wizard first decision label.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "move.step.who.title", message: "Who is this money going to?", context: "Move wizard destination decision heading.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.step.who.description", message: "Choose one of your agents or another account.", context: "Move wizard destination decision guidance.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.step.amount.label", message: "How much", context: "Move wizard second decision label.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.step.amount.title", message: "How much should move?", context: "Move wizard amount decision heading.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.step.review.label", message: "Review", context: "Move wizard third decision label.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "move.step.review.title", message: "Review before you confirm", context: "Move wizard review decision heading.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.destination.other", message: "Another account", context: "Destination choice for an account outside your agents.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "move.destination.other.hint", message: "Paste the account identifier", context: "Field label for entering an outside account.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "move.destination.loading", message: "Checking your agents", context: "Move destination state while the agent list loads.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "move.destination.offline", message: "Your agents can't be refreshed while you're offline. You can still use another account.", context: "Move destination fallback when the agent list cannot refresh without a connection.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "move.destination.unavailable", message: "Your agents can't be shown right now. You can still use another account.", context: "Move destination fallback when the agent list fails to load.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "move.source.unavailable", message: "Your account is not ready to move money yet", context: "Move quote refusal when this device has no activated account reference.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.amount.hint", message: "Amount in base units of {currency}", context: "Field label for the amount to move.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.summary.to", message: "To", context: "Live summary label for the chosen destination.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "move.summary.amount", message: "Amount", context: "Live summary label for the chosen amount.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.summary.fee", message: "Fee", context: "Live summary label for the quoted fee.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.summary.route", message: "Route", context: "Live summary label for the resolved route.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "move.route.automatic", message: "Chosen automatically", context: "The route resolver picks the mechanism without user input.", surface: "default", kind: "body", moneyAdjacent: false },
  { key: "move.review.what", message: "What will happen", context: "Review heading introducing the plain-language quote.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.review.fee", message: "About {estimate} in fees, and never more than {ceiling}", context: "Fee estimate with its ceiling on the review screen.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.review.arrival", message: "Expected to arrive by {arrival}", context: "Arrival expectation on the review screen.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.review.expires", message: "This price is good until {expires}", context: "Quote expiry shown before committing.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.quote.send-to-account", message: "Send money to another account", context: "Service quote description for an account transfer.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.quote.fund-agent", message: "Add money to your agent", context: "Service quote description for funding an agent.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.quote.return-from-agent", message: "Return money from your agent", context: "Service quote description for reclaiming from an agent.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.irreversible.send-to-account", message: "Once it reaches the other account, this move can't be pulled back", context: "Irreversibility warning shown before committing.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.stage.send-to-account", message: "Sending to the other account", context: "Move journey stage for the outbound leg.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.stage.return-from-agent", message: "Returning money from your agent", context: "Move journey stage for the reclaim leg.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.mechanism.fund", message: "Adding money to your agent", context: "Automatically resolved route wording for fund.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.mechanism.allocate", message: "Setting money aside", context: "Automatically resolved route wording for allocate.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.mechanism.return", message: "Returning money to your account", context: "Automatically resolved route wording for return.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.mechanism.transfer", message: "Sending between accounts", context: "Automatically resolved route wording for transfer.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.result.receipt", message: "Backed by a LayerX receipt", context: "Shown only when verified receipt evidence backs the result.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.result.receipt_reference", message: "Receipt {number}", context: "Label for one ordered verified receipt reference in move result details.", surface: "technical", kind: "body", moneyAdjacent: true },
  { key: "move.result.checking", message: "We're checking what happened", context: "Move result when the commit response was lost and the same attempt is being recovered.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.result.checking.body", message: "Don't start this move again. Check the result using the same attempt when you're connected.", context: "Locked recovery guidance after a move commit response is lost.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.result.check", message: "Check result", context: "Recover a move with its original request key without starting another effect.", surface: "default", kind: "action", moneyAdjacent: true },
  { key: "move.result.updates_offline", message: "Updates are paused while you're offline. The latest confirmed state is still shown.", context: "Honest in-flight move status when journey refresh loses connectivity.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.result.updates_unavailable", message: "The latest update can't be shown yet. The latest confirmed state is still shown.", context: "Honest in-flight move status when journey refresh fails.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.result.money_left", message: "Money left your account", context: "Honest refusal detail when money moved before the stop.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.result.money_stayed", message: "No money left your account", context: "Honest refusal detail when nothing moved.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "move.result.change", message: "Make a change", context: "Follow the refusal's change path.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "move.result.start_again", message: "Start another move", context: "Begin a fresh move after a finished journey.", surface: "default", kind: "action", moneyAdjacent: true },
  { key: "move.result.home", message: "Back to home", context: "Leave the move result for the home screen.", surface: "default", kind: "action", moneyAdjacent: false },
  { key: "error.move.no-route", message: "There's no route to that destination right now, so nothing was sent", context: "Typed refusal when the resolver finds no route.", surface: "default", kind: "body", moneyAdjacent: true },
  { key: "error.move.quote-expired", message: "That price expired before you confirmed, so nothing moved. Review the fresh details and try again", context: "Typed conflict when committing an expired quote.", surface: "default", kind: "body", moneyAdjacent: true },
] as const satisfies readonly CopyEntry[];

const catalog = new Map<string, CopyEntry>(
  copyEntries.map((entry): [string, CopyEntry] => [entry.key, entry]),
);

export function human_copy_catalog(): ReadonlyMap<string, CopyEntry> {
  return catalog;
}

export function copyEntry(key: string): CopyEntry {
  const entry = catalog.get(key);
  if (entry === undefined) {
    throw new Error(`Unknown copy key: ${key}`);
  }
  return entry;
}
