import { spawn } from "node:child_process";
import { isAbsolute } from "node:path";
import type { MirrorCandidate, MirrorReadPolicy } from "./mirror.js";

const MAX_REQUEST=40*1024*1024,MAX_RESPONSE=1024*1024;
const MAX_U64=18_446_744_073_709_551_615n;
export interface ExecutableMirrorVerification {readonly level:string;readonly batchNumber:bigint;readonly headerDigest:Uint8Array;readonly evidenceDigest:Uint8Array;readonly sourceId:string;readonly target:string;readonly canonicalPosition:string;readonly provenance:"Canonical"|"Reorged";readonly latestBatch?:bigint;readonly batchLag:string;readonly failoverCount:number;readonly agreeingSources:number;readonly checkpointLevel:"unavailable"}
export class ExecutableMirrorError extends Error{public constructor(public readonly code:string){super(`mirror verification refused: ${code}`);this.name="ExecutableMirrorError";}}
function hex(value:Uint8Array):string{return Array.from(value,(byte)=>byte.toString(16).padStart(2,"0")).join("");}
function bytes(value:unknown):Uint8Array{if(typeof value!=="string"||!/^[0-9a-f]{64}$/u.test(value))throw new ExecutableMirrorError("malformed");return Uint8Array.from(value.match(/../gu)??[],(part)=>Number.parseInt(part,16));}
function decimal(value:unknown):bigint{if(typeof value!=="string"||!/^[1-9]\d*$/u.test(value))throw new ExecutableMirrorError("malformed");const result=BigInt(value);if(result>MAX_U64)throw new ExecutableMirrorError("malformed");return result;}
function text(value:unknown,maximum=2048):string{if(typeof value!=="string"||value.length===0||Buffer.byteLength(value)>maximum)throw new ExecutableMirrorError("malformed");return value;}
function small(value:unknown,minimum:number,maximum:number):number{if(typeof value!=="number"||!Number.isSafeInteger(value)||value<minimum||value>maximum)throw new ExecutableMirrorError("malformed");return value;}
function candidate(value:MirrorCandidate){if(!Number.isSafeInteger(value.source)||value.source<0||value.source>7||value.commitment.length!==32)throw new ExecutableMirrorError("configuration");return{source:value.source,commitment_hex:hex(value.commitment)};}
function policy(value:MirrorReadPolicy):unknown{if(value.kind==="exact")return{kind:"exact",candidate:candidate(value.candidate)};const candidates=value.candidates.map(candidate);return value.kind==="agreement"?{kind:value.kind,candidates,minimum:value.minimum}:{kind:value.kind,candidates};}

export class LocalMirrorExecutableVerifier{
  public constructor(private readonly executable:string,private readonly configuration:string,private readonly timeoutMs=120_000){if(!isAbsolute(executable)||!isAbsolute(configuration)||timeoutMs<100||timeoutMs>120_000)throw new ExecutableMirrorError("configuration");}
  public receipt(batchNumber:bigint,sourcePolicy:MirrorReadPolicy,canonicalReceipt:Uint8Array):Promise<ExecutableMirrorVerification>{return this.verify(batchNumber,sourcePolicy,{kind:"receipt",canonical_hex:hex(canonicalReceipt)});}
  public state(batchNumber:bigint,sourcePolicy:MirrorReadPolicy,canonicalState:Uint8Array,canonicalProof:Uint8Array):Promise<ExecutableMirrorVerification>{return this.verify(batchNumber,sourcePolicy,{kind:"state",canonical_hex:hex(canonicalState),proof_hex:hex(canonicalProof)});}
  private verify(batchNumber:bigint,sourcePolicy:MirrorReadPolicy,evidence:unknown):Promise<ExecutableMirrorVerification>{if(batchNumber<=0n||batchNumber>MAX_U64)throw new ExecutableMirrorError("configuration");const request=JSON.stringify({batch_number:batchNumber.toString(),evidence,policy:policy(sourcePolicy)});if(Buffer.byteLength(request)>MAX_REQUEST)throw new ExecutableMirrorError("bounds");return new Promise((resolve,reject)=>{const child=spawn(this.executable,[this.configuration],{stdio:["pipe","pipe","ignore"],windowsHide:true});let output="",size=0,settled=false;const finish=(error?:Error,value?:ExecutableMirrorVerification)=>{if(settled)return;settled=true;clearTimeout(timer);if(error===undefined&&value!==undefined)resolve(value);else reject(error??new ExecutableMirrorError("unavailable"));};const timer=setTimeout(()=>{child.kill("SIGKILL");finish(new ExecutableMirrorError("unavailable"));},this.timeoutMs);child.on("error",()=>finish(new ExecutableMirrorError("unavailable")));child.stdout.on("data",(chunk:Buffer)=>{size+=chunk.length;if(size>MAX_RESPONSE){child.kill("SIGKILL");finish(new ExecutableMirrorError("bounds"));return;}output+=chunk.toString("utf8");});child.on("close",()=>{try{const response=JSON.parse(output)as Record<string,unknown>;if(response.ok!==true)throw new ExecutableMirrorError(typeof response.error==="string"?response.error:"unavailable");const item=response.verification as Record<string,unknown>;const provenance=item.provenance;if(provenance!=="Canonical"&&provenance!=="Reorged"||item.checkpointLevel!=="unavailable")throw new ExecutableMirrorError("malformed");finish(undefined,Object.freeze({level:text(item.level,64),batchNumber:decimal(item.batchNumber),headerDigest:bytes(item.headerDigest),evidenceDigest:bytes(item.evidenceDigest),sourceId:text(item.sourceId,64),target:text(item.target),canonicalPosition:text(item.canonicalPosition),provenance,...(item.latestBatch===null||item.latestBatch===undefined?{}:{latestBatch:decimal(item.latestBatch)}),batchLag:text(item.batchLag,64),failoverCount:small(item.failoverCount,0,8),agreeingSources:small(item.agreeingSources,1,8),checkpointLevel:"unavailable"}));}catch(error){finish(error instanceof ExecutableMirrorError?error:new ExecutableMirrorError("malformed"));}});child.stdin.end(request);});}
}
