[package]
name = "layerx-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
layerx-types = { path = "../layerx-types" }
layerx-wire = { path = "../layerx-wire" }
layerx-proof = { path = "../layerx-proof" }

[lints]
workspace = true
