from .production import IdempotencyKey, PlatformPlane, ProductionTransport, SecretBytes

class LayerXKeyCredential:
    def __init__(self, key_id: str, secret: SecretBytes) -> None: ...
    def use(self) -> str: ...

class AgentHttpTransport(ProductionTransport):
    def __init__(self, endpoint: str, *, credential: LayerXKeyCredential | None = ..., timeout: float = ..., maximum_response_bytes: int = ...) -> None: ...
    def call(self, plane: PlatformPlane, operation: object, request: object, idempotency_key: IdempotencyKey | None) -> object: ...
