[package]
name="layerx-anchor-context-reference"
version="0.1.0"
edition="2021"
publish=false
[workspace]
[lib]
crate-type=["cdylib"]
[dependencies]
layerx-program-sdk={path="../../../sdk/rust"}
layerx-porting-solana-guest={path="../guest"}
[profile.release]
opt-level="z"
lto=true
codegen-units=1
panic="abort"
strip=true
[lints.rust]
unsafe_code="deny"
