[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"

[net]
offline = true

[target.wasm32-unknown-unknown]
rustflags = [
    "-C",
    "target-feature=-reference-types",
    "-C",
    "link-arg=--compress-relocations",
]
