name: Paxeer / Mock Balances Build Check

on:
  pull_request:
    branches:
      - main
      - release/**
    paths:
      - 'paxeer-network/**'
      - '.github/workflows/paxeer-mock-balances-build.yml'
  merge_group:
    branches:
      - main
      - release/**
  push:
    branches:
      - main
      - release/**
    paths:
      - 'paxeer-network/**'
      - '.github/workflows/paxeer-mock-balances-build.yml'

defaults:
  run:
    working-directory: paxeer-network

jobs:
  mock-balances-build:
    name: Compile with Mock Balances
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: '1.25.6'
          cache-dependency-path: paxeer-network/go.sum

      - name: Build with Mock Balances
        run: make install-mock-balances
