name: Paxeer / golangci-lint
on:
  push:
    tags:
      - 'paxeer-network/v*'
    branches:
      - main
      - release/**
    paths:
      - 'paxeer-network/**'
      - '.github/workflows/paxeer-golangci.yml'
  pull_request:
    paths:
      - 'paxeer-network/**'
      - '.github/workflows/paxeer-golangci.yml'
  merge_group:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: '1.25.6'
          cache-dependency-path: paxeer-network/go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8
        with:
          version: v2.8.0
          args: --timeout 10m0s
          working-directory: paxeer-network
